import mongoose from 'mongoose';
import { config } from '../config';
import { connectDB } from '../config/db';
import { User, MenuCategory, MenuItem, Coupon, RestaurantSettings, InventoryItem } from '../models';

export const seedDatabase = async () => {
  try {
    console.log('[Seed] Connecting to database...');
    await connectDB();
    console.log('[Seed] Connected to MongoDB');

    // 1. Seed Admin User
    console.log('[Seed] Seeding Admin User...');
    await User.deleteMany({ email: config.adminDefaultEmail.toLowerCase() });
    const admin = await User.create({
      name: 'Gharowa Head Admin',
      email: config.adminDefaultEmail.toLowerCase(),
      password: config.adminDefaultPassword,
      phone: '01973255888',
      role: 'super_admin',
      isActive: true,
    });
    console.log(`[Seed] Super Admin created: ${admin.email}`);

    // Create a demo Kitchen Staff user
    await User.deleteMany({ email: 'kitchen@gharowa.com' });
    await User.create({
      name: 'Motijheel Head Chef',
      email: 'kitchen@gharowa.com',
      password: 'Kitchen@Gharowa1972',
      phone: '01973255889',
      role: 'kitchen_staff',
      isActive: true,
    });

    // 2. Seed 15 Menu Categories
    console.log('[Seed] Seeding 15 Menu Categories...');
    await MenuCategory.deleteMany({});
    const categoriesData = [
      { nameBn: 'খিচুড়ি', nameEn: 'Khichuri', slug: 'khichuri', displayOrder: 1, icon: 'Flame', isActive: true },
      { nameBn: 'কাচ্চি ও বিরিয়ানি', nameEn: 'Biryani', slug: 'biryani', displayOrder: 2, icon: 'Utensils', isActive: true },
      { nameBn: 'তেহারি', nameEn: 'Tehari', slug: 'tehari', displayOrder: 3, icon: 'Utensils', isActive: true },
      { nameBn: 'পোলাও', nameEn: 'Polao', slug: 'polao', displayOrder: 4, icon: 'Wheat', isActive: true },
      { nameBn: 'খাসির মাংস', nameEn: 'Mutton', slug: 'mutton', displayOrder: 5, icon: 'Flame', isActive: true },
      { nameBn: 'গরুর মাংস', nameEn: 'Beef', slug: 'beef', displayOrder: 6, icon: 'Flame', isActive: true },
      { nameBn: 'চিকেন', nameEn: 'Chicken', slug: 'chicken', displayOrder: 7, icon: 'Utensils', isActive: true },
      { nameBn: 'মাছের পদ', nameEn: 'Fish', slug: 'fish', displayOrder: 8, icon: 'Fish', isActive: true },
      { nameBn: 'সাদা ভাত ও ফ্রাইড রাইস', nameEn: 'Rice', slug: 'rice', displayOrder: 9, icon: 'Wheat', isActive: true },
      { nameBn: 'ঝোল ও কারি', nameEn: 'Curry', slug: 'curry', displayOrder: 10, icon: 'Flame', isActive: true },
      { nameBn: 'স্ন্যাক্স ও সমুচা', nameEn: 'Snacks', slug: 'snacks', displayOrder: 11, icon: 'Cookie', isActive: true },
      { nameBn: 'পানীয় ও বোরহানি', nameEn: 'Drinks', slug: 'drinks', displayOrder: 12, icon: 'Coffee', isActive: true },
      { nameBn: 'মিষ্টি ও ডেজার্ট', nameEn: 'Desserts', slug: 'desserts', displayOrder: 13, icon: 'Cake', isActive: true },
      { nameBn: 'স্পেশাল কম্বো', nameEn: 'Combos', slug: 'combos', displayOrder: 14, icon: 'Package', isActive: true },
      { nameBn: 'স্পেশাল আইটেম', nameEn: 'Special Items', slug: 'special-items', displayOrder: 15, icon: 'Sparkles', isActive: true },
    ];
    const createdCategories = await MenuCategory.insertMany(categoriesData);
    const catMap: { [slug: string]: mongoose.Types.ObjectId } = {};
    createdCategories.forEach((c) => {
      catMap[c.slug] = c._id as mongoose.Types.ObjectId;
    });

    // 3. Seed 68 Realistic Demo Menu Items
    console.log('[Seed] Seeding 68 Realistic Demo Menu Items...');
    await MenuItem.deleteMany({});
    const menuItemsData = [
      // ==================== KHICHURI (1-6) ====================
      {
        nameBn: 'খাসির ভুনা খিচুড়ি',
        nameEn: 'Mutton Khichuri',
        slug: 'mutton-khichuri',
        category: catMap['khichuri'],
        price: 280,
        originalPrice: 320,
        descriptionBn: '১৯৭২ সালের ঐতিহ্যবাহী গোপন মসলায় রান্না করা খাঁটি দেশি খাসির মাংসের তুলতুলে ভুনা খিচুড়ি। সুগন্ধি চিনিগুঁড়া চাল ও খাঁটি গাওয়া ঘিয়ে তৈরি।',
        descriptionEn: 'Fragrant basmati and chinigura rice cooked with tender mutton, aromatic spices and rich flavors. A traditional Bengali favorite.',
        image: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?q=80&w=800&auto=format&fit=crop',
        galleryImages: [
          'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?q=80&w=800&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1546833999-b9f581a1996d?q=80&w=800&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?q=80&w=800&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1589302168068-964664d93dc0?q=80&w=800&auto=format&fit=crop',
        ],
        spiceLevel: 2,
        isAvailable: true,
        isBestseller: true,
        isFeatured: true,
        preparationTimeMinutes: 15,
        dietaryTags: ['Heritage Special', 'Best Seller', '100% Halal'],
        displayOrder: 1,
        rating: 4.9,
        reviewsCount: 124,
        portions: [
          { nameBn: 'রেগুলার (১ জন)', nameEn: 'Regular (1 Person)', price: 280, servingSize: '1 Person' },
          { nameBn: 'লার্জ (১-২ জন)', nameEn: 'Large (1-2 Person)', price: 420, servingSize: '1-2 Person' },
          { nameBn: 'ফ্যামিলি (৩-৪ জন)', nameEn: 'Family (3-4 Person)', price: 820, servingSize: '3-4 Person' },
        ],
        addOns: [
          { nameBn: 'অতিরিক্ত খাসির মাংস', nameEn: 'Extra Mutton', price: 80 },
          { nameBn: 'অতিরিক্ত ডিম', nameEn: 'Extra Egg', price: 20 },
          { nameBn: 'সালাদ', nameEn: 'Salad', price: 30 },
          { nameBn: 'বোরহানি (২০০ মি.লি.)', nameEn: 'Borhani (200ml)', price: 50 },
        ],
        nutritionFacts: { calories: '450 kcal', protein: '18 g', carbs: '52 g', fat: '15 g', fiber: '2 g' },
        aboutDishBn: 'প্রতিদিনের টাটকা খাসির মাংস ও ঘরোয়া গোপন মসলায় দম পদ্ধতিতে রান্না করা হয়।',
        aboutDishEn: 'Slow-cooked in dum style using fresh tender mutton and Gharowa secret recipe spices.',
      },
      {
        nameBn: 'বিফ ভুনা খিচুড়ি',
        nameEn: 'Beef Khichuri',
        slug: 'beef-khichuri',
        category: catMap['khichuri'],
        price: 240,
        originalPrice: 280,
        descriptionBn: 'সুস্বাদু নরম গরুর মাংসের সাথে ভুনা মুগ ডাল ও সুগন্ধি চালের স্পেশাল ভুনা খিচুড়ি।',
        descriptionEn: 'Tender beef chunks cooked with roasted moong dal and aromatic chinigura rice.',
        image: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?q=80&w=800&auto=format&fit=crop',
        galleryImages: ['https://images.unsplash.com/photo-1589302168068-964664d93dc0?q=80&w=800&auto=format&fit=crop'],
        spiceLevel: 2,
        isAvailable: true,
        isBestseller: false,
        isFeatured: false,
        displayOrder: 2,
        rating: 4.8,
        reviewsCount: 95,
        portions: [
          { nameBn: 'রেগুলার', nameEn: 'Regular', price: 240, servingSize: '1 Person' },
          { nameBn: 'লার্জ', nameEn: 'Large', price: 360, servingSize: '1-2 Person' },
        ],
        addOns: [
          { nameBn: 'অতিরিক্ত ডিম', nameEn: 'Extra Egg', price: 20 },
          { nameBn: 'বোরহানি', nameEn: 'Borhani', price: 50 },
        ],
      },
      {
        nameBn: 'চিকেন ভুনা খিচুড়ি',
        nameEn: 'Chicken Khichuri',
        slug: 'chicken-khichuri',
        category: catMap['khichuri'],
        price: 220,
        originalPrice: 250,
        descriptionBn: 'দেশি স্বাদের রসালো চিকেন ও সোনালী মুগ ডালের খাঁটি ঘরোয়া ভুনা খিচুড়ি।',
        descriptionEn: 'Juicy tender chicken slow-cooked with aromatic roasted lentil rice.',
        image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?q=80&w=800&auto=format&fit=crop',
        galleryImages: ['https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?q=80&w=800&auto=format&fit=crop'],
        spiceLevel: 1,
        isAvailable: true,
        isBestseller: false,
        isFeatured: true,
        displayOrder: 3,
        rating: 4.7,
        reviewsCount: 88,
        portions: [
          { nameBn: 'রেগুলার', nameEn: 'Regular', price: 220, servingSize: '1 Person' },
          { nameBn: 'লার্জ', nameEn: 'Large', price: 330, servingSize: '1-2 Person' },
        ],
      },
      {
        nameBn: 'ডিম ভুনা খিচুড়ি',
        nameEn: 'Egg Khichuri',
        slug: 'egg-khichuri',
        category: catMap['khichuri'],
        price: 180,
        originalPrice: 200,
        descriptionBn: 'ঘিয়ে ভাজা ২টি ডিম ও স্পেশাল মসলায় তৈরি ক্লাসিক ভুনা খিচুড়ি।',
        descriptionEn: 'Classic bhuna khichuri served with two golden fried spiced eggs.',
        image: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 1,
        isAvailable: true,
        displayOrder: 4,
        rating: 4.6,
        reviewsCount: 52,
      },
      {
        nameBn: 'সবজি খিচুড়ি',
        nameEn: 'Vegetable Khichuri',
        slug: 'vegetable-khichuri',
        category: catMap['khichuri'],
        price: 160,
        descriptionBn: 'টাটকা নানা রকমের মৌসুমি সবজি ও ডালের পুষ্টিকর স্বাস্থ্যকর খিচুড়ি।',
        descriptionEn: 'Healthy and wholesome khichuri cooked with seasonal fresh vegetables and lentils.',
        image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 1,
        isAvailable: true,
        displayOrder: 5,
        rating: 4.5,
        reviewsCount: 41,
      },
      {
        nameBn: 'ঘরোয়া স্পেশাল খাসির লেগ খিচুড়ি',
        nameEn: 'Special Gharowa Khichuri',
        slug: 'special-gharowa-khichuri',
        category: catMap['khichuri'],
        price: 450,
        originalPrice: 500,
        descriptionBn: 'সম্পূর্ণ খাসির আস্ত লেগ পিসসহ শাহি স্বাদের স্পেশাল ঘরোয়া ভুনা খিচুড়ি।',
        descriptionEn: 'Signature feast with whole tender mutton leg served on aromatic royal bhuna khichuri.',
        image: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 2,
        isAvailable: true,
        isBestseller: true,
        isFeatured: true,
        displayOrder: 6,
        rating: 5.0,
        reviewsCount: 210,
      },

      // ==================== BIRYANI (7-12) ====================
      {
        nameBn: 'ঐতিহ্যবাহী খাসির কাচ্চি বিরিয়ানি',
        nameEn: 'Kacchi Biryani',
        slug: 'kacchi-biryani',
        category: catMap['biryani'],
        price: 320,
        originalPrice: 360,
        descriptionBn: 'খাঁটি বাসমতী চাল, গাওয়া ঘি ও জাফরানে ম্যারিনেট করা নরম খাসির মাংস ও আলু দিয়ে দম কাচ্চি।',
        descriptionEn: 'Traditional Old Dhaka dum kacchi biryani layered with succulent mutton and golden spiced potato.',
        image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 2,
        isAvailable: true,
        isBestseller: true,
        isFeatured: true,
        displayOrder: 7,
        rating: 4.9,
        reviewsCount: 180,
      },
      {
        nameBn: 'খাসির দম বিরিয়ানি',
        nameEn: 'Mutton Biryani',
        slug: 'mutton-biryani',
        category: catMap['biryani'],
        price: 300,
        originalPrice: 340,
        descriptionBn: 'সুগন্ধি পোলাও চালের সাথে মাটির হাঁড়িতে দমে রান্না করা নরম খাসির মাংসের বিরিয়ানি।',
        descriptionEn: 'Dum cooked aromatic mutton biryani enriched with saffron, fried onions, and whole spices.',
        image: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 2,
        isAvailable: true,
        isBestseller: true,
        isFeatured: true,
        displayOrder: 8,
        rating: 4.8,
        reviewsCount: 145,
      },
      {
        nameBn: 'চিকেন দম বিরিয়ানি',
        nameEn: 'Chicken Biryani',
        slug: 'chicken-biryani',
        category: catMap['biryani'],
        price: 250,
        originalPrice: 280,
        descriptionBn: 'সুগন্ধি চিনিগুঁড়া চাল ও রসালো চিকেন দিয়ে প্রস্তুত সুস্বাদু বিরিয়ানি ও আলু।',
        descriptionEn: 'Delicious aromatic chicken biryani prepared with premium spices and tender chicken.',
        image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 1,
        isAvailable: true,
        isBestseller: true,
        isFeatured: true,
        displayOrder: 9,
        rating: 4.7,
        reviewsCount: 110,
      },
      {
        nameBn: 'বিফ বিরিয়ানি',
        nameEn: 'Beef Biryani',
        slug: 'beef-biryani',
        category: catMap['biryani'],
        price: 260,
        descriptionBn: 'স্পেশাল বিরিয়ানি মসলায় রান্না করা সুস্বাদু গরুর মাংসের বিরিয়ানি।',
        descriptionEn: 'Flavorful beef biryani cooked with rich spices and tender beef cubes.',
        image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 2,
        isAvailable: true,
        displayOrder: 10,
        rating: 4.7,
        reviewsCount: 78,
      },
      {
        nameBn: 'ঘরোয়া স্পেশাল শাহি বিরিয়ানি',
        nameEn: 'Special Biryani',
        slug: 'special-biryani',
        category: catMap['biryani'],
        price: 350,
        descriptionBn: 'খাসির মাংস, চিকেন রোস্ট ও সিদ্ধ ডিম সমন্বয়ে প্রস্তুত রাজকীয় বিরিয়ানি প্ল্যাটার।',
        descriptionEn: 'Royal feast combining tender mutton, chicken roast and boiled egg on aromatic biryani.',
        image: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 2,
        isAvailable: true,
        isFeatured: true,
        displayOrder: 11,
        rating: 4.9,
        reviewsCount: 95,
      },
      {
        nameBn: 'মাটির হাঁড়ি বিরিয়ানি',
        nameEn: 'Handi Biryani',
        slug: 'handi-biryani',
        category: catMap['biryani'],
        price: 340,
        descriptionBn: 'মাটির সিল করা পাত্রে কাঠের আঁচে দমে রান্না করা খাঁটি ঢাকাইয়া বিরিয়ানি।',
        descriptionEn: 'Slow-cooked in sealed clay handi over slow embers for unforgettable smoky aroma.',
        image: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 2,
        isAvailable: true,
        displayOrder: 12,
        rating: 4.8,
        reviewsCount: 65,
      },

      // ==================== TEHARI (13-16) ====================
      {
        nameBn: 'পুরান ঢাকার বিফ তেহারি',
        nameEn: 'Beef Tehari',
        slug: 'beef-tehari',
        category: catMap['tehari'],
        price: 260,
        originalPrice: 290,
        descriptionBn: 'খাঁটি সরিষার তেলে ছোট ছোট নরম গরুর মাংসের টুকরো ও কাঁচামরিচে রান্না করা আসল ঢাকাইয়া তেহারি।',
        descriptionEn: 'Authentic Old Dhaka style mustard oil tehari cooked with bite-sized tender beef pieces and green chilies.',
        image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 2,
        isAvailable: true,
        isBestseller: true,
        isFeatured: true,
        displayOrder: 13,
        rating: 4.8,
        reviewsCount: 160,
      },
      {
        nameBn: 'খাসির ভুনা তেহারি',
        nameEn: 'Mutton Tehari',
        slug: 'mutton-tehari',
        category: catMap['tehari'],
        price: 290,
        descriptionBn: 'খাসির নরম মাংস ও খাঁটি ঘানি ভাঙা সরিষার তেলের সুস্বাদু খাসির তেহারি।',
        descriptionEn: 'Fragrant mustard-infused tehari prepared with fresh mutton cubes and aromatic rice.',
        image: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 2,
        isAvailable: true,
        displayOrder: 14,
        rating: 4.7,
        reviewsCount: 84,
      },
      {
        nameBn: 'চিকেন তেহারি',
        nameEn: 'Chicken Tehari',
        slug: 'chicken-tehari',
        category: catMap['tehari'],
        price: 230,
        descriptionBn: 'সরিষার তেলে হালকা ঝালে রান্না করা নরম মুরগির মাংসের তেহারি।',
        descriptionEn: 'Light spiced chicken tehari prepared with mustard oil and chinigura rice.',
        image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 1,
        isAvailable: true,
        displayOrder: 15,
        rating: 4.6,
        reviewsCount: 62,
      },
      {
        nameBn: 'ঘরোয়া স্পেশাল শাহি তেহারি',
        nameEn: 'Special Tehari',
        slug: 'special-tehari',
        category: catMap['tehari'],
        price: 310,
        descriptionBn: 'অতিরিক্ত গরুর মাংস, আলু বোখারা ও কাঁচামরিচের সুবাসে তৈরি স্পেশাল তেহারি।',
        descriptionEn: 'Gharowa special recipe tehari loaded with extra beef and traditional spices.',
        image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 2,
        isAvailable: true,
        displayOrder: 16,
        rating: 4.9,
        reviewsCount: 92,
      },

      // ==================== POLAO (17-21) ====================
      {
        nameBn: 'বিয়েবাড়ির মোরগ পোলাও',
        nameEn: 'Morog Polao',
        slug: 'morog-polao',
        category: catMap['polao'],
        price: 260,
        originalPrice: 300,
        descriptionBn: 'ঘিয়ে ভাজা সুগন্ধি পোলাও ও আস্ত শাহি চিকেন লেগ রোস্ট ও ডিম।',
        descriptionEn: 'Classic Bengali wedding style Morog Polao with whole spiced chicken leg roast.',
        image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 1,
        isAvailable: true,
        isBestseller: true,
        isFeatured: true,
        displayOrder: 17,
        rating: 4.8,
        reviewsCount: 130,
      },
      {
        nameBn: 'শাহি খাসির পোলাও',
        nameEn: 'Mutton Polao',
        slug: 'mutton-polao',
        category: catMap['polao'],
        price: 290,
        descriptionBn: 'খাসির নরম মাংস দিয়ে রান্না করা সুস্বাদু হালকা মসলার শাহি পোলাও।',
        descriptionEn: 'Fragrant ghee-cooked polao rice with tender succulent mutton pieces.',
        image: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 1,
        isAvailable: true,
        displayOrder: 18,
        rating: 4.7,
        reviewsCount: 75,
      },
      {
        nameBn: 'চিকেন পোলাও',
        nameEn: 'Chicken Polao',
        slug: 'chicken-polao',
        category: catMap['polao'],
        price: 240,
        descriptionBn: 'ঘিয়ে ভাজা সুগন্ধি চাল ও তুলতুলে চিকেন পিস।',
        descriptionEn: 'Light and fragrant polao rice served with tender chicken piece.',
        image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 1,
        isAvailable: true,
        displayOrder: 19,
        rating: 4.6,
        reviewsCount: 58,
      },
      {
        nameBn: 'প্লেন সুগন্ধি পোলাও',
        nameEn: 'Plain Polao',
        slug: 'plain-polao',
        category: catMap['polao'],
        price: 150,
        descriptionBn: 'খাঁটি গাওয়া ঘিয়ে রান্না করা সুগন্ধি চিনিগুঁড়া চালের পোলাও ও বেরেস্তা।',
        descriptionEn: 'Aromatic chinigura rice cooked in pure ghee with crispy golden fried onions.',
        image: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 0,
        isAvailable: true,
        displayOrder: 20,
        rating: 4.7,
        reviewsCount: 48,
      },
      {
        nameBn: 'শাহি স্পেশাল জাফরানি পোলাও',
        nameEn: 'Special Polao',
        slug: 'special-polao',
        category: catMap['polao'],
        price: 200,
        descriptionBn: 'জাফরান, কাজুবাদাম ও কিশমিশ দিয়ে সাজানো শাহি জাফরানি পোলাও।',
        descriptionEn: 'Royal saffron infused polao garnished with cashews and golden raisins.',
        image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 0,
        isAvailable: true,
        displayOrder: 21,
        rating: 4.8,
        reviewsCount: 39,
      },

      // ==================== MUTTON (22-26) ====================
      {
        nameBn: 'শাহি মাটন রেজালা',
        nameEn: 'Mutton Rezala',
        slug: 'mutton-rezala',
        category: catMap['mutton'],
        price: 320,
        originalPrice: 360,
        descriptionBn: 'পোস্তদানা, টকদই ও শাহি মসলায় রান্না করা নরম তুলতুলে খাসির মাংসের রেজালা।',
        descriptionEn: 'Royal Mughlai style mutton curry with rich yogurt, cashew and poppy seed gravy.',
        image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 1,
        isAvailable: true,
        isBestseller: true,
        isFeatured: true,
        displayOrder: 22,
        rating: 4.9,
        reviewsCount: 140,
      },
      {
        nameBn: 'খাসির আলু কারি',
        nameEn: 'Mutton Curry',
        slug: 'mutton-curry',
        category: catMap['mutton'],
        price: 300,
        descriptionBn: 'ঘরোয়া স্টাইলের খাসির মাংসের পাতলা ঝোল ও নরম আলু।',
        descriptionEn: 'Traditional home-style mutton curry with tender potatoes and rich gravy.',
        image: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 2,
        isAvailable: true,
        displayOrder: 23,
        rating: 4.7,
        reviewsCount: 88,
      },
      {
        nameBn: 'খাসির কষা ভুনা',
        nameEn: 'Mutton Bhuna',
        slug: 'mutton-bhuna',
        category: catMap['mutton'],
        price: 310,
        descriptionBn: 'পেঁয়াজ ও আদা-রসুন কষিয়ে গাঢ় মসলায় তৈরি খাসির স্পেশাল ভুনা।',
        descriptionEn: 'Slow-cooked mutton roasted in rich onion and thick spiced gravy.',
        image: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 3,
        isAvailable: true,
        displayOrder: 24,
        rating: 4.8,
        reviewsCount: 96,
      },
      {
        nameBn: 'স্পেশাল মাটন কষা',
        nameEn: 'Mutton Kasha',
        slug: 'mutton-kasha',
        category: catMap['mutton'],
        price: 330,
        descriptionBn: 'ঝাল ঝাল খাসির কষা মাংস — পোলাও ও পরোটার সাথে অসাধারণ স্বাদ।',
        descriptionEn: 'Fiery and deeply caramelized slow-cooked mutton kasha.',
        image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 3,
        isAvailable: true,
        displayOrder: 25,
        rating: 4.8,
        reviewsCount: 72,
      },
      {
        nameBn: 'মাটন দো পেঁয়াজা',
        nameEn: 'Mutton Do Pyaza',
        slug: 'mutton-do-pyaza',
        category: catMap['mutton'],
        price: 310,
        descriptionBn: 'দুই ধাপে কষানো পেঁয়াজ ও নরম খাসির মাংসের সুস্বাদু ডিশ।',
        descriptionEn: 'Mutton prepared with double-cooked caramelized onions and whole spices.',
        image: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 2,
        isAvailable: true,
        displayOrder: 26,
        rating: 4.7,
        reviewsCount: 54,
      },

      // ==================== BEEF (27-31) ====================
      {
        nameBn: 'স্পেশাল বিফ ভুনা',
        nameEn: 'Beef Bhuna',
        slug: 'beef-bhuna',
        category: catMap['beef'],
        price: 260,
        originalPrice: 290,
        descriptionBn: 'নরম গরুর মাংস গাঢ় মসলা ও সুবাসিত তেলে কষিয়ে তৈরি সুস্বাদু বিফ ভুনা।',
        descriptionEn: 'Tender beef cubes slow-cooked in intensely caramelized spice reduction.',
        image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 2,
        isAvailable: true,
        isBestseller: true,
        displayOrder: 27,
        rating: 4.8,
        reviewsCount: 115,
      },
      {
        nameBn: 'বিফ আলু কারি',
        nameEn: 'Beef Curry',
        slug: 'beef-curry',
        category: catMap['beef'],
        price: 250,
        descriptionBn: 'ঘরোয়া স্বাদে আলু ও গরুর মাংসের রসালো পাতলা ঝোল।',
        descriptionEn: 'Comforting home-style beef curry cooked with fresh potatoes.',
        image: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 2,
        isAvailable: true,
        displayOrder: 28,
        rating: 4.7,
        reviewsCount: 80,
      },
      {
        nameBn: 'চট্টগ্রামের ঐতিহ্যবাহী বিফ কালা ভুনা',
        nameEn: 'Beef Kala Bhuna',
        slug: 'beef-kala-bhuna',
        category: catMap['beef'],
        price: 320,
        originalPrice: 360,
        descriptionBn: 'আসল চট্টগ্রামের ঐতিহ্যবাহী কালো রঙের সুস্বাদু নরম বিফ কালা ভুনা।',
        descriptionEn: 'Legendary Chittagong style black-roasted tender beef prepared with 18 authentic spices.',
        image: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 3,
        isAvailable: true,
        isBestseller: true,
        isFeatured: true,
        displayOrder: 29,
        rating: 5.0,
        reviewsCount: 220,
      },
      {
        nameBn: 'শাহি বিফ রেজালা',
        nameEn: 'Beef Rezala',
        slug: 'beef-rezala',
        category: catMap['beef'],
        price: 270,
        descriptionBn: 'পোস্তদানা ও বাদাম বাটার শাহি গ্রেভিতে তৈরি বিফ রেজালা।',
        descriptionEn: 'Mughlai style beef cooked in smooth poppy seed and yogurt gravy.',
        image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 1,
        isAvailable: true,
        displayOrder: 30,
        rating: 4.7,
        reviewsCount: 65,
      },
      {
        nameBn: 'বিফ কষা',
        nameEn: 'Beef Kasha',
        slug: 'beef-kasha',
        category: catMap['beef'],
        price: 280,
        descriptionBn: 'কাঁচামরিচ ও পেঁয়াজে কষানো সুস্বাদু ঝাল বিফ কষা।',
        descriptionEn: 'Rich spiced slow-roasted beef with green chilies.',
        image: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 3,
        isAvailable: true,
        displayOrder: 31,
        rating: 4.8,
        reviewsCount: 71,
      },

      // ==================== CHICKEN (32-37) ====================
      {
        nameBn: 'বিয়েবাড়ির শাহি চিকেন রোস্ট',
        nameEn: 'Chicken Roast',
        slug: 'chicken-roast',
        category: catMap['chicken'],
        price: 280,
        originalPrice: 310,
        descriptionBn: 'ঘিয়ে ভাজা আস্ত চিকেন লেগ শাহি পোস্ত ও বাদামের ঘন গ্রেভিতে তৈরি ক্লাসিক বিয়েবাড়ির রোস্ট।',
        descriptionEn: 'Traditional wedding-style whole chicken leg roast in creamy spiced nutty gravy.',
        image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 1,
        isAvailable: true,
        isBestseller: true,
        isFeatured: true,
        displayOrder: 32,
        rating: 4.9,
        reviewsCount: 165,
      },
      {
        nameBn: 'দেশি চিকেন কারি',
        nameEn: 'Chicken Curry',
        slug: 'chicken-curry',
        category: catMap['chicken'],
        price: 220,
        descriptionBn: 'আলু ও টাটকা মসলায় রান্না করা ঘরোয়া চিকেন কারি।',
        descriptionEn: 'Flavorful Bengali home-style chicken curry with potatoes.',
        image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 2,
        isAvailable: true,
        displayOrder: 33,
        rating: 4.7,
        reviewsCount: 90,
      },
      {
        nameBn: 'চিকেন ভুনা',
        nameEn: 'Chicken Bhuna',
        slug: 'chicken-bhuna',
        category: catMap['chicken'],
        price: 230,
        descriptionBn: 'পেঁয়াজ ও আদা রসুনের ঘন গ্রেভিতে রান্না করা চিকেন ভুনা।',
        descriptionEn: 'Succulent chicken pieces cooked in thick savory onion gravy.',
        image: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 2,
        isAvailable: true,
        displayOrder: 34,
        rating: 4.7,
        reviewsCount: 68,
      },
      {
        nameBn: 'চিকেন কষা',
        nameEn: 'Chicken Kasha',
        slug: 'chicken-kasha',
        category: catMap['chicken'],
        price: 240,
        descriptionBn: 'ঝাল মসলায় কষিয়ে রান্না করা স্পেশাল চিকেন কষা।',
        descriptionEn: 'Deep roasted spicy chicken with caramelized onion paste.',
        image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 3,
        isAvailable: true,
        displayOrder: 35,
        rating: 4.8,
        reviewsCount: 77,
      },
      {
        nameBn: 'শাহি চিকেন রেজালা',
        nameEn: 'Chicken Rezala',
        slug: 'chicken-rezala',
        category: catMap['chicken'],
        price: 250,
        descriptionBn: 'শাহি বাদাম ও টকদইয়ের সাদা গ্রেভিতে তৈরি চিকেন রেজালা।',
        descriptionEn: 'Mughlai chicken rezala in velvety cashew and poppy seed gravy.',
        image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 1,
        isAvailable: true,
        displayOrder: 36,
        rating: 4.7,
        reviewsCount: 59,
      },
      {
        nameBn: 'চিকেন ঝাল ফ্রাই',
        nameEn: 'Chicken Jhal Fry',
        slug: 'chicken-jhal-fry',
        category: catMap['chicken'],
        price: 220,
        descriptionBn: 'কাঁচামরিচ, টমেটো ও ক্যাপসিকামে ভাজা ঝাল চিকেন।',
        descriptionEn: 'Spicy chicken stir-fry with fresh green chilies and onions.',
        image: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 3,
        isAvailable: true,
        displayOrder: 37,
        rating: 4.6,
        reviewsCount: 64,
      },

      // ==================== FISH (38-42) ====================
      {
        nameBn: 'রুই মাছের দোপেঁয়াজা',
        nameEn: 'Rui Fish Curry',
        slug: 'rui-fish-curry',
        category: catMap['fish'],
        price: 250,
        descriptionBn: 'টাটকা রুই মাছের বড় পেটি কষানো পেঁয়াজ ও টমেটো গ্রেভিতে রান্না।',
        descriptionEn: 'Fresh Rui fish steak cooked in rich caramelized onion gravy.',
        image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 2,
        isAvailable: true,
        displayOrder: 38,
        rating: 4.7,
        reviewsCount: 55,
      },
      {
        nameBn: 'কাতলা মাছের কালিয়া',
        nameEn: 'Katla Fish Curry',
        slug: 'katla-fish-curry',
        category: catMap['fish'],
        price: 260,
        descriptionBn: 'শাহি মসলায় রান্না করা কাতলা মাছের ঐতিহ্যবাহী কালিয়া।',
        descriptionEn: 'Rich and hearty Katla fish kalia prepared with aromatic spices.',
        image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 2,
        isAvailable: true,
        displayOrder: 39,
        rating: 4.8,
        reviewsCount: 48,
      },
      {
        nameBn: 'পদ্মার সরিষা ইলিশ ভুনা',
        nameEn: 'Ilish Bhuna',
        slug: 'ilish-bhuna',
        category: catMap['fish'],
        price: 400,
        originalPrice: 450,
        descriptionBn: 'খাঁটি সরিষার পেস্ট ও কাঁচামরিচে রান্না করা পদ্মার তাজা ইলিশের ভুনা।',
        descriptionEn: 'Padma River Hilsa fish steak cooked in authentic pungent mustard gravy.',
        image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 2,
        isAvailable: true,
        isBestseller: true,
        isFeatured: true,
        displayOrder: 40,
        rating: 5.0,
        reviewsCount: 190,
      },
      {
        nameBn: 'ইলিশ মাছের পাতলা ঝোল',
        nameEn: 'Ilish Curry',
        slug: 'ilish-curry',
        category: catMap['fish'],
        price: 380,
        descriptionBn: 'বেগুন ও কাঁচামরিচে ইলিশের খাঁটি ঐতিহ্যবাহী পাতলা ঝোল।',
        descriptionEn: 'Delicate Hilsa fish curry cooked with eggplant and green chilies.',
        image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 1,
        isAvailable: true,
        displayOrder: 41,
        rating: 4.8,
        reviewsCount: 68,
      },
      {
        nameBn: 'রূপচাঁদা ক্রিস্পি ফিশ ফ্রাই',
        nameEn: 'Fish Fry',
        slug: 'fish-fry',
        category: catMap['fish'],
        price: 350,
        descriptionBn: 'আস্ত রূপচাঁদা মাছের মুচমুচে ফ্রাই ও স্পেশাল চাটনি।',
        descriptionEn: 'Whole crispy golden fried Pomfret fish served with lemon and mint chutney.',
        image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 2,
        isAvailable: true,
        displayOrder: 42,
        rating: 4.8,
        reviewsCount: 82,
      },

      // ==================== RICE (43-46) ====================
      {
        nameBn: 'সাদা সুগন্ধি ভাত',
        nameEn: 'Plain Rice',
        slug: 'plain-rice',
        category: catMap['rice'],
        price: 50,
        descriptionBn: 'ঝরঝরে গরম সাদা নাজিরশাইল চালের ভাত।',
        descriptionEn: 'Steamed fluffy premium long-grain aromatic rice.',
        image: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 0,
        isAvailable: true,
        displayOrder: 43,
        rating: 4.6,
        reviewsCount: 40,
      },
      {
        nameBn: 'স্টিমড বাসমতী ভাত',
        nameEn: 'Steamed Rice',
        slug: 'steamed-rice',
        category: catMap['rice'],
        price: 80,
        descriptionBn: 'উন্নত মানের সুগন্ধি বাসমতী চালের স্টিমড ভাত।',
        descriptionEn: 'Aromatic steamed aged basmati rice.',
        image: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 0,
        isAvailable: true,
        displayOrder: 44,
        rating: 4.7,
        reviewsCount: 35,
      },
      {
        nameBn: 'স্পেশাল ফ্রাইড রাইস',
        nameEn: 'Special Fried Rice',
        slug: 'special-fried-rice',
        category: catMap['rice'],
        price: 180,
        descriptionBn: 'চিকেন, ডিম ও সবজি সমন্বয়ে তৈরি স্পেশাল ফ্রাইড রাইস।',
        descriptionEn: 'Wok-tossed fried rice with chicken, eggs, and crisp vegetables.',
        image: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 1,
        isAvailable: true,
        displayOrder: 45,
        rating: 4.6,
        reviewsCount: 47,
      },
      {
        nameBn: 'এগ ফ্রাইড রাইস',
        nameEn: 'Egg Fried Rice',
        slug: 'egg-fried-rice',
        category: catMap['rice'],
        price: 160,
        descriptionBn: 'ডিম ও গোলমরিচ দিয়ে তৈরি সুস্বাদু ফ্রাইড রাইস।',
        descriptionEn: 'Classic scrambled egg fried rice with spring onions.',
        image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 1,
        isAvailable: true,
        displayOrder: 46,
        rating: 4.5,
        reviewsCount: 38,
      },

      // ==================== SNACKS (47-52) ====================
      {
        nameBn: 'চিকেন সমুচা (৪ পিস)',
        nameEn: 'Chicken Samosa',
        slug: 'chicken-samosa',
        category: catMap['snacks'],
        price: 120,
        descriptionBn: 'মুচমুচে খাস্তা পাতায় মোড়ানো কিমা চিকেনের স্পেশাল সমুচা।',
        descriptionEn: 'Crispy golden triangular pastries filled with seasoned minced chicken.',
        image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 2,
        isAvailable: true,
        displayOrder: 47,
        rating: 4.8,
        reviewsCount: 85,
      },
      {
        nameBn: 'বিফ সমুচা (৪ পিস)',
        nameEn: 'Beef Samosa',
        slug: 'beef-samosa',
        category: catMap['snacks'],
        price: 140,
        descriptionBn: 'গরুর কিমা ও পেঁয়াজের সুস্বাদু পুরে তৈরি খাস্তা বিফ সমুচা।',
        descriptionEn: 'Crispy pastries stuffed with spiced minced beef filling.',
        image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 2,
        isAvailable: true,
        displayOrder: 48,
        rating: 4.9,
        reviewsCount: 92,
      },
      {
        nameBn: 'আলু-সবজি সিঙ্গাড়া (৪ পিস)',
        nameEn: 'Vegetable Singara',
        slug: 'vegetable-singara',
        category: catMap['snacks'],
        price: 60,
        descriptionBn: 'মৌসুমি ফুলকপি ও বাদাম-আলুর খাস্তা গরম সিঙ্গাড়া।',
        descriptionEn: 'Traditional Bengali singara filled with spiced potatoes and peanuts.',
        image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 1,
        isAvailable: true,
        displayOrder: 49,
        rating: 4.7,
        reviewsCount: 110,
      },
      {
        nameBn: 'স্পেশাল চিকেন রোল',
        nameEn: 'Chicken Roll',
        slug: 'chicken-roll',
        category: catMap['snacks'],
        price: 100,
        descriptionBn: 'চিকেন ও গোলমরিচের পুরে তৈরি মুচমুচে স্প্রিং রোল।',
        descriptionEn: 'Crispy golden roll stuffed with juicy chicken and vegetables.',
        image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 1,
        isAvailable: true,
        displayOrder: 50,
        rating: 4.7,
        reviewsCount: 64,
      },
      {
        nameBn: 'স্পেশাল বিফ রোল',
        nameEn: 'Beef Roll',
        slug: 'beef-roll',
        category: catMap['snacks'],
        price: 120,
        descriptionBn: 'গরুর মাংসের কষা কিমায় তৈরি স্পেশাল বিফ রোল।',
        descriptionEn: 'Savory breadcrumbed roll loaded with spiced minced beef.',
        image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 2,
        isAvailable: true,
        displayOrder: 51,
        rating: 4.8,
        reviewsCount: 58,
      },
      {
        nameBn: 'চিকেন পাকোড়া',
        nameEn: 'Chicken Pakora',
        slug: 'chicken-pakora',
        category: catMap['snacks'],
        price: 150,
        descriptionBn: 'বেসন ও মসলায় মাখিয়ে ডিপ ফ্রাই করা মুচমুচে চিকেন পাকোড়া।',
        descriptionEn: 'Crispy deep-fried chicken fritters coated with seasoned gram flour.',
        image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 2,
        isAvailable: true,
        displayOrder: 52,
        rating: 4.7,
        reviewsCount: 70,
      },

      // ==================== DRINKS (53-58) ====================
      {
        nameBn: 'ঘরোয়া স্পেশাল বোরহানি (গ্লাস)',
        nameEn: 'Borhani',
        slug: 'borhani',
        category: catMap['drinks'],
        price: 60,
        originalPrice: 70,
        descriptionBn: 'টকদই, পুদিনা পাতা, বিট লবণ ও গোপন হজমি মসলায় তৈরি আসল ঘরোয়া স্পেশাল বোরহানি।',
        descriptionEn: 'Signature digestive spiced yogurt drink infused with fresh mint and roasted cumin.',
        image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 1,
        isAvailable: true,
        isBestseller: true,
        isFeatured: true,
        displayOrder: 53,
        rating: 5.0,
        reviewsCount: 310,
      },
      {
        nameBn: 'শাহি মিষ্টি লাচ্ছি',
        nameEn: 'Sweet Lassi',
        slug: 'sweet-lassi',
        category: catMap['drinks'],
        price: 80,
        descriptionBn: 'ঘন মিষ্টি দই ও পেস্তাবাদামের সরভরা শাহি লাচ্ছি।',
        descriptionEn: 'Creamy sweet yogurt drink topped with crushed pistachios.',
        image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 0,
        isAvailable: true,
        displayOrder: 54,
        rating: 4.8,
        reviewsCount: 112,
      },
      {
        nameBn: 'ম্যাঙ্গো লাচ্ছি',
        nameEn: 'Mango Lassi',
        slug: 'mango-lassi',
        category: catMap['drinks'],
        price: 100,
        descriptionBn: 'পাকা আমের পাল্প ও দইয়ের মন মাতানো রিফ্রেশিং লাচ্ছি।',
        descriptionEn: 'Refreshing blend of sweet mango pulp and chilled creamy yogurt.',
        image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 0,
        isAvailable: true,
        displayOrder: 55,
        rating: 4.9,
        reviewsCount: 88,
      },
      {
        nameBn: 'ফ্রেশ লেমনেড / পুদিনা শরবত',
        nameEn: 'Fresh Lemonade',
        slug: 'fresh-lemonade',
        category: catMap['drinks'],
        price: 50,
        descriptionBn: 'টাটকা লেবুর রস ও পুদিনা পাতার বরফ ঠান্ডা শরবত।',
        descriptionEn: 'Chilled freshly squeezed lemonade infused with crushed mint leaves.',
        image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 0,
        isAvailable: true,
        displayOrder: 56,
        rating: 4.7,
        reviewsCount: 52,
      },
      {
        nameBn: 'সফট ড্রিঙ্কস (ক্যান)',
        nameEn: 'Soft Drinks',
        slug: 'soft-drinks',
        category: catMap['drinks'],
        price: 40,
        descriptionBn: 'কোকাকোলা / স্প্রাইট / ফান্টা (২৫০ মি.লি. ক্যান)।',
        descriptionEn: 'Chilled canned soft drinks (Coca Cola, Sprite, Fanta).',
        image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 0,
        isAvailable: true,
        displayOrder: 57,
        rating: 4.6,
        reviewsCount: 65,
      },
      {
        nameBn: 'মিনারেল ওয়াটার (৫০০ মি.লি.)',
        nameEn: 'Mineral Water',
        slug: 'mineral-water',
        category: catMap['drinks'],
        price: 25,
        descriptionBn: 'বিশুদ্ধ বোতলজাত মিনারেল ড্রিংকিং ওয়াটার।',
        descriptionEn: 'Purified bottled drinking water (500ml).',
        image: 'https://images.unsplash.com/photo-1548839140-29a749e1bc4e?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 0,
        isAvailable: true,
        displayOrder: 58,
        rating: 4.9,
        reviewsCount: 44,
      },

      // ==================== DESSERTS (59-64) ====================
      {
        nameBn: 'শাহি জাফরানি ফিরনি',
        nameEn: 'Firni',
        slug: 'firni',
        category: catMap['desserts'],
        price: 80,
        originalPrice: 100,
        descriptionBn: 'মাটির পাত্রে জমা ক্ষীর, পেস্তা ও কাজুবাদামে তৈরি ঐতিহ্যবাহী শাহি জাফরানি ফিরনি।',
        descriptionEn: 'Royal slow-cooked rice pudding served in clay pot with saffron and dry fruits.',
        image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 0,
        isAvailable: true,
        isBestseller: true,
        isFeatured: true,
        displayOrder: 59,
        rating: 4.9,
        reviewsCount: 175,
      },
      {
        nameBn: 'শাহি বিয়েবাড়ির জর্দা',
        nameEn: 'Jorda',
        slug: 'jorda',
        category: catMap['desserts'],
        price: 60,
        descriptionBn: 'ঘিয়ে ভাজা সুগন্ধি বাসমতী চাল, মোরব্বা ও ছোট মিষ্টি সমন্বয়ে ঐতিহ্যবাহী বিয়েবাড়ির জর্দা।',
        descriptionEn: 'Sweet celebration rice dish garnished with baby sweets, nuts and candied fruits.',
        image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 0,
        isAvailable: true,
        displayOrder: 60,
        rating: 4.8,
        reviewsCount: 95,
      },
      {
        nameBn: 'বগুড়ার ঐতিহ্যবাহী মিষ্টি দই',
        nameEn: 'Sweet Yogurt',
        slug: 'sweet-yogurt',
        category: catMap['desserts'],
        price: 70,
        descriptionBn: 'মাটির হাঁড়িতে তৈরি বগুড়ার খাঁটি লাল মিষ্টি দই।',
        descriptionEn: 'Authentic Bogura style sweet caramelized yogurt in clay pot.',
        image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 0,
        isAvailable: true,
        displayOrder: 61,
        rating: 4.9,
        reviewsCount: 120,
      },
      {
        nameBn: 'শাহি গুলাব জামুন (২ পিস)',
        nameEn: 'Gulab Jamun',
        slug: 'gulab-jamun',
        category: catMap['desserts'],
        price: 80,
        descriptionBn: 'গরম এলাচ চিনির রসে ভেজানো নরম তুলতুলে গুলাব জামুন।',
        descriptionEn: 'Warm soft milk solids dumplings soaked in fragrant rose-cardamom syrup.',
        image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 0,
        isAvailable: true,
        displayOrder: 62,
        rating: 4.8,
        reviewsCount: 88,
      },
      {
        nameBn: 'কুমিল্লার স্পেশাল রসমালাই',
        nameEn: 'Rasmalai',
        slug: 'rasmalai',
        category: catMap['desserts'],
        price: 120,
        descriptionBn: 'খাঁটি ক্ষীর ও ছানার তুলতুলে মিষ্টি সমন্বয়ে কুমিল্লার বিখ্যাত রসমালাই।',
        descriptionEn: 'Famous Comilla style cottage cheese patties soaked in saffron clotted cream.',
        image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 0,
        isAvailable: true,
        isBestseller: true,
        displayOrder: 63,
        rating: 5.0,
        reviewsCount: 140,
      },
      {
        nameBn: 'প্রিমিয়াম আইসক্রিম কাপ',
        nameEn: 'Ice Cream',
        slug: 'ice-cream',
        category: catMap['desserts'],
        price: 100,
        descriptionBn: 'ভ্যানিলা / চকলেট স্বাদের ঠান্ডা প্রিমিয়াম আইসক্রিম।',
        descriptionEn: 'Premium rich vanilla or chocolate ice cream.',
        image: 'https://images.unsplash.com/photo-1501443762994-82bd5dace89a?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 0,
        isAvailable: true,
        displayOrder: 64,
        rating: 4.7,
        reviewsCount: 60,
      },

      // ==================== COMBOS (65-68) ====================
      {
        nameBn: 'মাটন খিচুড়ি স্পেশাল কম্বো',
        nameEn: 'Mutton Khichuri Combo',
        slug: 'mutton-khichuri-combo',
        category: catMap['combos'],
        price: 350,
        originalPrice: 410,
        descriptionBn: 'খাসির ভুনা খিচুড়ি + ডিম ভুনা + সালাদ + ঘরোয়া স্পেশাল বোরহানি।',
        descriptionEn: 'Signature Mutton Khichuri served with Boiled Egg, Fresh Salad, and Borhani.',
        image: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 2,
        isAvailable: true,
        isBestseller: true,
        isFeatured: true,
        displayOrder: 65,
        rating: 5.0,
        reviewsCount: 280,
      },
      {
        nameBn: 'চিকেন বিরিয়ানি কম্বো',
        nameEn: 'Chicken Biryani Combo',
        slug: 'chicken-biryani-combo',
        category: catMap['combos'],
        price: 340,
        originalPrice: 390,
        descriptionBn: 'চিকেন বিরিয়ানি + শাহি কাবাব + বোরহানি + স্পেশাল ফিরনি।',
        descriptionEn: 'Chicken Biryani paired with Shahi Kebab, Borhani and Firni dessert.',
        image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 1,
        isAvailable: true,
        isBestseller: true,
        isFeatured: true,
        displayOrder: 66,
        rating: 4.9,
        reviewsCount: 195,
      },
      {
        nameBn: 'বিফ তেহারি কম্বো',
        nameEn: 'Beef Tehari Combo',
        slug: 'beef-tehari-combo',
        category: catMap['combos'],
        price: 330,
        originalPrice: 380,
        descriptionBn: 'বিফ তেহারি + বোরহানি + সিদ্ধ ডিম + শাহি জর্দা।',
        descriptionEn: 'Authentic Beef Tehari served with Borhani, Boiled Egg, and Jorda dessert.',
        image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 2,
        isAvailable: true,
        isFeatured: true,
        displayOrder: 67,
        rating: 4.8,
        reviewsCount: 155,
      },
      {
        nameBn: 'ঘরোয়া গ্র্যান্ড স্পেশাল কম্বো',
        nameEn: 'Gharowa Special Combo',
        slug: 'gharowa-special-combo',
        category: catMap['combos'],
        price: 450,
        originalPrice: 520,
        descriptionBn: 'খাসির ভুনা খিচুড়ি + চিকেন রোস্ট + আস্ত ডিম + বোরহানি + জাফরানি ফিরনি।',
        descriptionEn: 'The Ultimate Heritage Feast: Mutton Khichuri, Chicken Roast, Egg, Borhani, and Firni.',
        image: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 2,
        isAvailable: true,
        isBestseller: true,
        isFeatured: true,
        displayOrder: 68,
        rating: 5.0,
        reviewsCount: 340,
      },
    ];

    await MenuItem.insertMany(menuItemsData);
    console.log(`[Seed] 68 Demo Menu items seeded successfully.`);

    // 4. Seed Coupons
    console.log('[Seed] Seeding Coupons...');
    await Coupon.deleteMany({});
    await Coupon.create([
      {
        code: 'GH1972',
        titleBn: 'ঐতিহ্যের স্বাদ ৫০ টাকা ছাড়',
        titleEn: 'Heritage Special 50 BDT Off',
        descriptionBn: 'ন্যূনতম ৫০০ টাকার অর্ডারে প্রযোজ্য',
        descriptionEn: 'Applicable on orders over 500 BDT',
        discountType: 'fixed',
        discountValue: 50,
        minOrderAmount: 500,
        maxDiscountAmount: 50,
        startDate: new Date(),
        expiryDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
        maxUsageLimit: 1000,
        isActive: true,
      },
      {
        code: 'GHAROWA10',
        titleBn: '১০% বিশেষ ছাড়',
        titleEn: '10% Special Discount',
        descriptionBn: 'ন্যূনতম ৮০০ টাকার অর্ডারে প্রযোজ্য',
        descriptionEn: 'Applicable on orders over 800 BDT',
        discountType: 'percentage',
        discountValue: 10,
        minOrderAmount: 800,
        maxDiscountAmount: 200,
        startDate: new Date(),
        expiryDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
        maxUsageLimit: 1000,
        isActive: true,
      },
    ]);

    // 5. Seed Restaurant CMS Settings
    console.log('[Seed] Seeding Restaurant Settings CMS...');
    await RestaurantSettings.deleteMany({});
    await RestaurantSettings.create({
      restaurantNameBn: 'ঘরোয়া হোটেল এন্ড রেস্টুরেন্ট',
      restaurantNameEn: 'Gharowa Hotel & Restaurant',
      taglineBn: '১৯৭২ সাল থেকে মতিঝিলের ঐতিহ্যের স্বাদ',
      taglineEn: 'Serving Authentic Bengali Heritage Since 1972',
      phone: '+8801973255888',
      whatsappNumber: '8801973255888',
      email: 'info@gharowarestaurant.com',
      addressBn: '৯/সি মতিঝিল বা/এ, ঢাকা-১০০০ (মেট্রোরেল স্টেশন সংলগ্ন)',
      addressEn: '9/C Motijheel C/A, Dhaka-1000, Bangladesh',
      openingHoursBn: 'সকাল ৭:০০ - রাত ১১:৩০ (প্রতিদিন খোলা)',
      openingHoursEn: '7:00 AM - 11:30 PM (Open Everyday)',
      standardDeliveryFee: 60,
      freeDeliveryThreshold: 1500,
      minOrderAmount: 200,
      heroTitleBn: 'ঐতিহ্যবাহী খাসির ভুনা খিচুড়ি',
      heroTitleEn: 'AUTHENTIC MUTTON KHICHURI',
      heroSubtitleBn: '১৯৭২ সাল থেকে ঢাকার মতিঝিলের ঐতিহ্যবাহী খাসির ভুনা খিচুড়ি, লেগ খিচুড়ি, স্পেশাল কাচ্চি ও বোরহানি।',
      heroSubtitleEn: 'Traditional taste, rich aroma and perfectly cooked mutton. 50+ years of trust.',
      heroBadgeBn: 'ঐতিহ্যবাহী স্বাদ',
      heroBadgeEn: 'AUTHENTIC',
      heroImageUrl: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?q=80&w=1000&auto=format&fit=crop',
      heroPouringImageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?q=80&w=800&auto=format&fit=crop',
      heroCtaTextBn: 'অর্ডার করুন',
      heroCtaTextEn: 'Order Now',
      heroCtaLink: '/menu',
      aboutTitleBn: 'আমাদের ঐতিহ্য ও গল্প',
      aboutTitleEn: 'Our Heritage Story',
      aboutDescBn: '১৯৭২ সালে মতিঝিলের প্রাণকেন্দ্রে শুরু হয় ঘরোয়ার যাত্রা। বিগত ৫ দশকেরও বেশি সময় ধরে আমরা ধরে রেখেছি খাঁটি ঢাকাইয়া রান্নার অতুলনীয় ঐতিহ্য ও স্বাদ।',
      aboutDescEn: 'Gharowa Hotel & Restaurant started in 1972 with a simple goal — to serve authentic Bengali flavors with the best quality and love. Our Mutton Khichuri is our signature dish loved by thousands.',
      aboutImageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=1000&auto=format&fit=crop',
      aboutStats: [
        { labelBn: 'বছরের ঐতিহ্য', labelEn: 'Years Heritage', value: '50+' },
        { labelBn: 'সন্তুষ্ট ভোজনরসিক', labelEn: 'Happy Customers', value: '100K+' },
        { labelBn: 'খাঁটি উপাদান', labelEn: 'Fresh Ingredients', value: '100%' },
        { labelBn: 'গ্রাহক রেটিং', labelEn: 'Customer Rating', value: '4.9 ★' },
      ],
      chefName: 'Chef Rahman',
      chefDesignation: 'Executive Master Chef',
      chefBioBn: '২৫ বছরেরও বেশি রন্ধন অভিজ্ঞতায় ঐতিহ্যবাহী মসলা ও খাঁটি ঘরোয়া স্বাদের ধারক।',
      chefBioEn: 'Over 25 years of mastery in authentic slow-cooked traditional Bangladeshi heritage cuisine.',
      chefExperience: '25+ Years Experience',
      chefSpecialty: 'Dum Pukht & Heritage Khichuri',
      chefImageUrl: 'https://images.unsplash.com/photo-1577219491135-ce391730fb2c?q=80&w=800&auto=format&fit=crop',
      ownerName: 'Alhaj Md. Sirajuddin',
      ownerDesignation: 'Founder & Visionary (Since 1972)',
      ownerStoryBn: '১৯৭২ সালে মতিঝিলে ছোট্ট পরিসরে শুরু করা ঘরোয়া আজ ঢাকার ঐতিহ্যের অংশ। আমাদের অঙ্গীকার কেবল মান ও খাঁটি স্বাদ।',
      ownerStoryEn: 'Founded with the philosophy that great food brings families and hearts together with honesty and passion.',
      ownerQuoteBn: 'স্বাদ যেখানে স্মৃতি, তৃপ্তি যেখানে প্রতিশ্রুতি।',
      ownerQuoteEn: 'Where culinary tradition meets timeless hospitality.',
      ownerImageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=800&auto=format&fit=crop',
    });

    console.log('[Seed] Database seeded successfully with all 68 demo items and 15 categories!');
    process.exit(0);
  } catch (error) {
    console.error('[Seed] Database seed error:', error);
    process.exit(1);
  }
};

if (require.main === module) {
  seedDatabase();
}
