import mongoose from 'mongoose';
import { config } from '../config';
import { connectDB } from '../config/db';
import { User, MenuCategory, MenuItem, Coupon, RestaurantSettings, InventoryItem } from '../models';

export const seedDatabase = async () => {
  try {
    console.log('[Seed] Connecting to database...');
    await connectDB();
    console.log('[Seed] Connected to MongoDB');

    // 1. Seed Admin User
    console.log('[Seed] Seeding Admin User...');
    await User.deleteMany({ email: config.adminDefaultEmail.toLowerCase() });
    const admin = await User.create({
      name: 'Gharowa Head Admin',
      email: config.adminDefaultEmail.toLowerCase(),
      password: config.adminDefaultPassword,
      phone: '01973255888',
      role: 'super_admin',
      isActive: true,
    });
    console.log(`[Seed] Super Admin created: ${admin.email}`);

    // Create a demo Kitchen Staff user
    await User.deleteMany({ email: 'kitchen@gharowa.com' });
    await User.create({
      name: 'Motijheel Head Chef',
      email: 'kitchen@gharowa.com',
      password: 'Kitchen@Gharowa1972',
      phone: '01973255889',
      role: 'kitchen_staff',
      isActive: true,
    });

    // 2. Seed Authentic Menu Categories (Inspired by official menu board)
    console.log('[Seed] Seeding Menu Categories...');
    await MenuCategory.deleteMany({});
    const categoriesData = [
      { nameBn: 'সব খাবার', nameEn: 'All', slug: 'all', displayOrder: 0, icon: 'Utensils', isActive: true },
      { nameBn: 'খিচুড়ি ও বিরিয়ানি', nameEn: 'Khichuri & Biryani', slug: 'khichuri-biryani', displayOrder: 1, icon: 'Flame', isActive: true },
      { nameBn: 'সকালের নাস্তা', nameEn: 'Breakfast', slug: 'breakfast', displayOrder: 2, icon: 'Sun', isActive: true },
      { nameBn: 'দুপুর ও রাতের খাবার', nameEn: 'Lunch & Dinner', slug: 'main-course', displayOrder: 3, icon: 'Utensils', isActive: true },
      { nameBn: 'মাছের পদ', nameEn: 'Fish Items', slug: 'fish', displayOrder: 4, icon: 'Fish', isActive: true },
      { nameBn: 'কাবাব ও শর্মা', nameEn: 'Kabab & Shawarma', slug: 'kabab-grill', displayOrder: 5, icon: 'Flame', isActive: true },
      { nameBn: 'শাক ও ভর্তা', nameEn: 'Vorta & Greens', slug: 'vorta-greens', displayOrder: 6, icon: 'Leaf', isActive: true },
      { nameBn: 'নান, পরটা ও ভাত', nameEn: 'Breads & Rice', slug: 'breads-rice', displayOrder: 7, icon: 'Wheat', isActive: true },
      { nameBn: 'ডেজার্ট ও মিষ্টি', nameEn: 'Desserts', slug: 'desserts', displayOrder: 8, icon: 'Cake', isActive: true },
      { nameBn: 'পানীয় ও বোরহানি', nameEn: 'Drinks & Juices', slug: 'drinks', displayOrder: 9, icon: 'Coffee', isActive: true },
    ];
    const createdCategories = await MenuCategory.insertMany(categoriesData);
    const catMap: { [slug: string]: mongoose.Types.ObjectId } = {};
    createdCategories.forEach((c) => {
      catMap[c.slug] = c._id as mongoose.Types.ObjectId;
    });

    // 3. Seed Menu Items from Authentic Price Board Reference
    console.log('[Seed] Seeding Menu Items from authentic menu board...');
    await MenuItem.deleteMany({});
    const menuItemsData = [
      // ==================== KHICHURI & BIRYANI ====================
      {
        nameBn: 'খাসির ভুনা খিচুড়ি',
        nameEn: 'Mutton Bhuna Khichuri',
        slug: 'mutton-khichuri',
        category: catMap['khichuri-biryani'],
        price: 290,
        originalPrice: 330,
        descriptionBn: 'ঘরোয়ার সিগনেচার পদ — ১৯৭২ সাল থেকে ঐতিহ্যবাহী গোপন মসলায় রান্না করা খাঁটি দেশি খাসির মাংসের নরম ভুনা খিচুড়ি।',
        descriptionEn: 'Gharowa signature dish — fragrant rice and roasted moong dal slow-cooked with tender mutton pieces.',
        image: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?q=80&w=800&auto=format&fit=crop',
        galleryImages: [
          'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?q=80&w=800&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1546833999-b9f581a1996d?q=80&w=800&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?q=80&w=800&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1589302168068-964664d93dc0?q=80&w=800&auto=format&fit=crop',
        ],
        spiceLevel: 2,
        isAvailable: true,
        isBestseller: true,
        isFeatured: true,
        displayOrder: 1,
        rating: 4.9,
        reviewsCount: 260,
        portions: [
          { nameBn: 'রেগুলার (১ জন)', nameEn: 'Regular (1 Person)', price: 290, servingSize: '1 Person' },
          { nameBn: 'লার্জ (১-২ জন)', nameEn: 'Large (1-2 Person)', price: 430, servingSize: '1-2 Person' },
          { nameBn: 'ফ্যামিলি (৩-৪ জন)', nameEn: 'Family (3-4 Person)', price: 850, servingSize: '3-4 Person' },
        ],
        addOns: [
          { nameBn: 'অতিরিক্ত খাসির মাংস', nameEn: 'Extra Mutton', price: 90 },
          { nameBn: 'অতিরিক্ত ডিম', nameEn: 'Extra Egg', price: 20 },
          { nameBn: 'সালাদ', nameEn: 'Salad', price: 30 },
          { nameBn: 'বোরহানি (১ গ্লাস)', nameEn: 'Borhani (1 Glass)', price: 50 },
        ],
        nutritionFacts: { calories: '480 kcal', protein: '22 g', carbs: '54 g', fat: '18 g', fiber: '3 g' },
      },
      {
        nameBn: 'খাসির লেগ খিচুড়ি (স্পেশাল)',
        nameEn: 'Special Mutton Leg Khichuri',
        slug: 'mutton-leg-khichuri',
        category: catMap['khichuri-biryani'],
        price: 550,
        originalPrice: 600,
        descriptionBn: 'সম্পূর্ণ আস্ত রসালো খাসির লেগ পিসসহ শাহি স্বাদের ঘরোয়া স্পেশাল ভুনা খিচুড়ি।',
        descriptionEn: 'Grand royal feast featuring a whole tender mutton leg on rich aromatic bhuna khichuri.',
        image: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 2,
        isAvailable: true,
        isBestseller: true,
        isFeatured: true,
        displayOrder: 2,
        rating: 5.0,
        reviewsCount: 310,
      },
      {
        nameBn: 'চিকেন ভুনা খিচুড়ি',
        nameEn: 'Chicken Bhuna Khichuri',
        slug: 'chicken-bhuna-khichuri',
        category: catMap['khichuri-biryani'],
        price: 250,
        descriptionBn: 'দেশি স্বাদের রসালো চিকেন ও সোনালী মুগ ডালের খাঁটি ঘরোয়া ভুনা খিচুড়ি।',
        descriptionEn: 'Flavorful chicken slow-cooked with aromatic roasted moong dal khichuri.',
        image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 1,
        isAvailable: true,
        isFeatured: true,
        displayOrder: 3,
        rating: 4.8,
        reviewsCount: 140,
      },
      {
        nameBn: 'স্পেশাল খাসির কাচ্চি',
        nameEn: 'Special Mutton Kacchi Biryani',
        slug: 'special-mutton-kacchi',
        category: catMap['khichuri-biryani'],
        price: 290,
        originalPrice: 320,
        descriptionBn: 'সুগন্ধি বাসমতী চাল, গাওয়া ঘি ও জাফরানে ম্যারিনেট করা নরম খাসির মাংস ও আলু দিয়ে দম কাচ্চি।',
        descriptionEn: 'Authentic Old Dhaka dum kacchi biryani prepared with tender mutton and spiced potato.',
        image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 2,
        isAvailable: true,
        isBestseller: true,
        isFeatured: true,
        displayOrder: 4,
        rating: 4.9,
        reviewsCount: 220,
      },
      {
        nameBn: 'স্পেশাল চিকেন বিরিয়ানি',
        nameEn: 'Special Chicken Biryani',
        slug: 'special-chicken-biryani',
        category: catMap['khichuri-biryani'],
        price: 240,
        descriptionBn: 'সুগন্ধি চাল ও বড় চিকেন পিস সমন্বয়ে তৈরি ঐতিহ্যবাহী চিকেন বিরিয়ানি।',
        descriptionEn: 'Fragrant and mouthwatering spiced chicken biryani with boiled egg.',
        image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 1,
        isAvailable: true,
        isFeatured: true,
        displayOrder: 5,
        rating: 4.8,
        reviewsCount: 175,
      },
      {
        nameBn: 'পুরান ঢাকার বিফ তেহারি',
        nameEn: 'Beef Tehari',
        slug: 'beef-tehari',
        category: catMap['khichuri-biryani'],
        price: 260,
        descriptionBn: 'খাঁটি সরিষার তেলে ছোট ছোট নরম গরুর মাংসের টুকরো ও কাঁচামরিচে রান্না করা আসল ঢাকাইয়া তেহারি।',
        descriptionEn: 'Authentic mustard oil infused beef tehari cooked with green chilies and tender beef cubes.',
        image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 2,
        isAvailable: true,
        isBestseller: true,
        isFeatured: true,
        displayOrder: 6,
        rating: 4.9,
        reviewsCount: 190,
      },

      // ==================== BREAKFAST (সকালের নাস্তা) ====================
      {
        nameBn: 'পাতলা নান',
        nameEn: 'Patla Naan',
        slug: 'patla-naan',
        category: catMap['breakfast'],
        price: 20,
        descriptionBn: 'তন্দুরে তাজা সেঁকা নরম ও গরম পাতলা নান রুটি।',
        descriptionEn: 'Freshly baked thin soft tandoori naan.',
        image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 0,
        isAvailable: true,
        displayOrder: 7,
        rating: 4.7,
        reviewsCount: 80,
      },
      {
        nameBn: 'প্লেন পরটা',
        nameEn: 'Plain Paratha',
        slug: 'plain-paratha',
        category: catMap['breakfast'],
        price: 20,
        descriptionBn: 'মুচমুচে গরম ভাজা খাস্তা পরটা।',
        descriptionEn: 'Crispy layered golden fried plain paratha.',
        image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 0,
        isAvailable: true,
        displayOrder: 8,
        rating: 4.8,
        reviewsCount: 110,
      },
      {
        nameBn: 'সবজি ভাজি',
        nameEn: 'Vegetable Bhaji',
        slug: 'vegetable-bhaji',
        category: catMap['breakfast'],
        price: 25,
        descriptionBn: 'টাটকা আলু, পেঁপে ও গাজরের সুস্বাদু সকালের ভাজি।',
        descriptionEn: 'Freshly prepared spiced mixed vegetable stir-fry.',
        image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 1,
        isAvailable: true,
        displayOrder: 9,
        rating: 4.6,
        reviewsCount: 75,
      },
      {
        nameBn: 'বুটের ডাল',
        nameEn: 'Booter Dal',
        slug: 'booter-dal',
        category: catMap['breakfast'],
        price: 35,
        descriptionBn: 'ঘিয়ে ফোড়ন দেওয়া সুস্বাদু ঘন বুটের ডাল।',
        descriptionEn: 'Slow-cooked Bengal gram lentil curry tempered with whole spices.',
        image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 1,
        isAvailable: true,
        displayOrder: 10,
        rating: 4.8,
        reviewsCount: 95,
      },
      {
        nameBn: 'খাসির পায়্যা',
        nameEn: 'Mutton Paya',
        slug: 'mutton-paya',
        category: catMap['breakfast'],
        price: 150,
        descriptionBn: 'সারারাত মৃদু আঁচে রান্না করা খাসির পায়্যা — সকালে নান বা পরোটার সাথে অমৃত।',
        descriptionEn: 'Traditional slow-simmered rich trotters soup seasoned with whole spices.',
        image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 2,
        isAvailable: true,
        isBestseller: true,
        displayOrder: 11,
        rating: 4.9,
        reviewsCount: 160,
      },
      {
        nameBn: 'খাসির পায়্যা নেহারী',
        nameEn: 'Mutton Paya Nehari',
        slug: 'mutton-paya-nehari',
        category: catMap['breakfast'],
        price: 150,
        descriptionBn: 'আদা কুচি ও কাঁচামরিচ সহ গরম মশলায় তৈরি ঐতিহ্যবাহী খাসির নেহারী।',
        descriptionEn: 'Rich and hearty slow-cooked mutton trotters stew garnished with fresh ginger.',
        image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 2,
        isAvailable: true,
        displayOrder: 12,
        rating: 4.9,
        reviewsCount: 145,
      },
      {
        nameBn: 'চিকেন স্যুপ',
        nameEn: 'Chicken Soup',
        slug: 'chicken-soup',
        category: catMap['breakfast'],
        price: 130,
        descriptionBn: 'দেশি মুরগির সুস্বাদু গরম পুষ্টিকর স্যুপ।',
        descriptionEn: 'Hot, nourishing chicken clear soup with herbs and light spices.',
        image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 1,
        isAvailable: true,
        displayOrder: 13,
        rating: 4.6,
        reviewsCount: 50,
      },
      {
        nameBn: 'খাসির কলিজা ভুনা',
        nameEn: 'Mutton Liver Bhuna',
        slug: 'mutton-kolija-bhuna',
        category: catMap['breakfast'],
        price: 160,
        descriptionBn: 'পেঁয়াজ ও আদা-রসুনে কষানো নরম খাসির কলিজা ভুনা।',
        descriptionEn: 'Tender mutton liver spiced and sauteed with caramelized onions.',
        image: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 2,
        isAvailable: true,
        displayOrder: 14,
        rating: 4.8,
        reviewsCount: 88,
      },
      {
        nameBn: 'খাসির ডালগোস্ত',
        nameEn: 'Mutton Dal Gosht',
        slug: 'mutton-dal-gosht',
        category: catMap['breakfast'],
        price: 160,
        descriptionBn: 'বুটের ডাল ও নরম খাসির মাংসের অপূর্ব সমন্বয়ে রান্না ডালগোস্ত।',
        descriptionEn: 'Hearty Bengal gram lentils cooked with tender mutton cubes.',
        image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 2,
        isAvailable: true,
        displayOrder: 15,
        rating: 4.7,
        reviewsCount: 65,
      },
      {
        nameBn: 'মুচমুচে সিঙ্গাড়া',
        nameEn: 'Singara',
        slug: 'singara',
        category: catMap['breakfast'],
        price: 20,
        descriptionBn: 'বাদাম ও ফুলকপির সুস্বাদু পুরে ভরা গরম গরম খাস্তা সিঙ্গাড়া।',
        descriptionEn: 'Golden crispy pastry stuffed with spiced potato, cauliflower and peanuts.',
        image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 1,
        isAvailable: true,
        displayOrder: 16,
        rating: 4.8,
        reviewsCount: 130,
      },

      // ==================== LUNCH & DINNER (দুপুর ও রাতের খাবার) ====================
      {
        nameBn: 'চিকেন ঝাল ফ্রাই',
        nameEn: 'Chicken Jhal Fry',
        slug: 'chicken-jhal-fry',
        category: catMap['main-course'],
        price: 170,
        descriptionBn: 'কাঁচামরিচ, পেঁয়াজ ও টমেটো সসে কষানো সুস্বাদু চিকেন ঝাল ফ্রাই।',
        descriptionEn: 'Spicy wok-fried chicken with fresh green chilies and onions.',
        image: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 3,
        isAvailable: true,
        displayOrder: 17,
        rating: 4.8,
        reviewsCount: 95,
      },
      {
        nameBn: 'খাসির দো-পিয়াজো',
        nameEn: 'Mutton Do Pyaza',
        slug: 'mutton-do-pyaza',
        category: catMap['main-course'],
        price: 240,
        descriptionBn: 'কষানো পেঁয়াজ ও শাহি গরম মসলায় তৈরি খাসির দো-পিয়াজো।',
        descriptionEn: 'Tender mutton cooked in double layers of caramelized onions and rich gravy.',
        image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 2,
        isAvailable: true,
        displayOrder: 18,
        rating: 4.8,
        reviewsCount: 110,
      },
      {
        nameBn: 'চিকেন মোসাল্লাম',
        nameEn: 'Chicken Musallam',
        slug: 'chicken-musallam',
        category: catMap['main-course'],
        price: 250,
        descriptionBn: 'শাহি মসলা ও বাদামের পেস্টে তৈরি রাজকীয় চিকেন মোসাল্লাম।',
        descriptionEn: 'Rich Mughlai style chicken cooked in fragrant nutty spiced gravy.',
        image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 1,
        isAvailable: true,
        displayOrder: 19,
        rating: 4.7,
        reviewsCount: 82,
      },
      {
        nameBn: 'খাসির লেগ রোস্ট',
        nameEn: 'Mutton Leg Roast',
        slug: 'mutton-leg-roast',
        category: catMap['main-course'],
        price: 380,
        descriptionBn: 'ঘিয়ে ভাজা খাসির আস্ত লেগ পিস শাহি পোস্ত বাদাম গ্রেভিতে তৈরি।',
        descriptionEn: 'Whole mutton leg roasted with royal spices and creamy gravy.',
        image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 2,
        isAvailable: true,
        isBestseller: true,
        displayOrder: 20,
        rating: 4.9,
        reviewsCount: 140,
      },
      {
        nameBn: 'খাসির রোস্ট',
        nameEn: 'Mutton Roast',
        slug: 'mutton-roast',
        category: catMap['main-course'],
        price: 270,
        descriptionBn: 'ঐতিহ্যবাহী শাহি স্বাদে রান্না করা খাসির নরম রোস্ট।',
        descriptionEn: 'Succulent mutton pieces slow-roasted in aromatic Mughlai gravy.',
        image: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 2,
        isAvailable: true,
        displayOrder: 21,
        rating: 4.8,
        reviewsCount: 90,
      },
      {
        nameBn: 'চিকেন রোস্ট',
        nameEn: 'Chicken Roast',
        slug: 'chicken-roast',
        category: catMap['main-course'],
        price: 170,
        descriptionBn: 'বিয়েবাড়ির শাহি মসলায় রান্না করা চিকেন লেগ রোস্ট।',
        descriptionEn: 'Traditional celebration style golden chicken leg roast.',
        image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 1,
        isAvailable: true,
        isFeatured: true,
        displayOrder: 22,
        rating: 4.9,
        reviewsCount: 180,
      },
      {
        nameBn: 'মুগ ডাল ভুনা',
        nameEn: 'Moong Dal Bhuna',
        slug: 'moong-dal-bhuna',
        category: catMap['main-course'],
        price: 40,
        descriptionBn: 'ঘিয়ে ভাজা সোনালী মুগ ডালের ঘন ভুনা।',
        descriptionEn: 'Roasted yellow moong dal cooked in thick savory ghee gravy.',
        image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 1,
        isAvailable: true,
        displayOrder: 23,
        rating: 4.7,
        reviewsCount: 60,
      },
      {
        nameBn: 'পাতলা ডাল',
        nameEn: 'Patla Dal',
        slug: 'patla-dal',
        category: catMap['main-course'],
        price: 25,
        descriptionBn: 'রসুন ও জিরার বাঘারে তৈরি ঐতিহ্যবাহী পাতলা মসুর ডাল।',
        descriptionEn: 'Traditional home-style red lentil soup tempered with garlic and cumin.',
        image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 0,
        isAvailable: true,
        displayOrder: 24,
        rating: 4.6,
        reviewsCount: 70,
      },
      {
        nameBn: 'স্পেশাল সবজি',
        nameEn: 'Special Sabji',
        slug: 'special-sabji',
        category: catMap['main-course'],
        price: 50,
        descriptionBn: 'মৌসুমি হরেক রকমের টাটকা সবজির স্পেশাল তরকারি।',
        descriptionEn: 'Delightful medley of seasonal fresh vegetables simmered with spices.',
        image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 1,
        isAvailable: true,
        displayOrder: 25,
        rating: 4.6,
        reviewsCount: 45,
      },

      // ==================== FISH (মাছ) ====================
      {
        nameBn: 'স্পেশাল সরিষা ইলিশ',
        nameEn: 'Special Shorshe Ilish',
        slug: 'special-shorshe-ilish',
        category: catMap['fish'],
        price: 500,
        originalPrice: 550,
        descriptionBn: 'পদ্মার টাটকা ইলিশের বড় টুকরো খাঁটি সরিষার তেলে কাঁচামরিচে রান্না।',
        descriptionEn: 'Fresh Padma River Hilsa fish steak cooked in rich pungent mustard sauce.',
        image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 2,
        isAvailable: true,
        isBestseller: true,
        isFeatured: true,
        displayOrder: 26,
        rating: 5.0,
        reviewsCount: 210,
      },
      {
        nameBn: 'রুই মাছ ভুনা',
        nameEn: 'Rui Fish Bhuna',
        slug: 'rui-fish',
        category: catMap['fish'],
        price: 250,
        descriptionBn: 'টাটকা রুই মাছের পেটি পেঁয়াজ ও টমেটোতে কষানো।',
        descriptionEn: 'Fresh Rui fish steak simmered in spiced onion-tomato reduction.',
        image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 2,
        isAvailable: true,
        displayOrder: 27,
        rating: 4.7,
        reviewsCount: 85,
      },
      {
        nameBn: 'রূপচাঁদা মাছ ফ্রাই',
        nameEn: 'Rupchanda Fish Fry',
        slug: 'rupchanda-fish',
        category: catMap['fish'],
        price: 350,
        descriptionBn: 'আস্ত রূপচাঁদা মাছের মুচমুচে ফ্রাই ও সালাদ।',
        descriptionEn: 'Whole crispy golden fried Pomfret fish served with lemon slices.',
        image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 2,
        isAvailable: true,
        displayOrder: 28,
        rating: 4.9,
        reviewsCount: 95,
      },
      {
        nameBn: 'বাইলা মাছ ভুনা',
        nameEn: 'Baila Fish Bhuna',
        slug: 'baila-fish',
        category: catMap['fish'],
        price: 350,
        descriptionBn: 'সুস্বাদু নদী ও সাগরের টাটকা বাইলা মাছের কষা ঝোল।',
        descriptionEn: 'Tender Baila fish cooked in aromatic savory Bengali gravy.',
        image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 2,
        isAvailable: true,
        displayOrder: 29,
        rating: 4.8,
        reviewsCount: 50,
      },
      {
        nameBn: 'আইড় মাছ ভুনা',
        nameEn: 'Air Fish Bhuna',
        slug: 'air-fish',
        category: catMap['fish'],
        price: 350,
        descriptionBn: 'নরম কাঁটাহীন আইড় মাছের লোভনীয় ভুনা।',
        descriptionEn: 'Boneless Air fish steak cooked in rich spicy onion curry.',
        image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 2,
        isAvailable: true,
        displayOrder: 30,
        rating: 4.8,
        reviewsCount: 55,
      },

      // ==================== KABAB & SHAWARMA (কাবাব ও শর্মা) ====================
      {
        nameBn: 'চিকেন বটি কাবাব',
        nameEn: 'Chicken Boti Kabab',
        slug: 'chicken-boti-kabab',
        category: catMap['kabab-grill'],
        price: 150,
        descriptionBn: 'কয়লার আঁচে পোড়া নরম ও মসলাদার চিকেন বটি।',
        descriptionEn: 'Tender boneless chicken chunks marinated in yogurt and chargrilled.',
        image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 2,
        isAvailable: true,
        displayOrder: 31,
        rating: 4.8,
        reviewsCount: 110,
      },
      {
        nameBn: 'খাসির বটি কাবাব',
        nameEn: 'Mutton Boti Kabab',
        slug: 'mutton-boti-kabab',
        category: catMap['kabab-grill'],
        price: 170,
        descriptionBn: 'খাসির নরম মাংসের শিক কাবাব — পুদিনা চাটনি সহ।',
        descriptionEn: 'Charcoal-grilled juicy spiced mutton boti skewers.',
        image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 2,
        isAvailable: true,
        displayOrder: 32,
        rating: 4.9,
        reviewsCount: 130,
      },
      {
        nameBn: 'চিকেন চাপ মাসালা',
        nameEn: 'Chicken Chaap Masala',
        slug: 'chicken-chaap-masala',
        category: catMap['kabab-grill'],
        price: 180,
        descriptionBn: 'তাওয়ায় ভাজা শাহি চিকেন চাপ ও ঘন বাদাম মসলা।',
        descriptionEn: 'Slow-fried flattened chicken cutlet in aromatic Mughlai chaap gravy.',
        image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 2,
        isAvailable: true,
        isBestseller: true,
        displayOrder: 33,
        rating: 4.9,
        reviewsCount: 145,
      },
      {
        nameBn: 'চিকেন চাপ ফ্রাই',
        nameEn: 'Chicken Chaap Fry',
        slug: 'chicken-chaap-fry',
        category: catMap['kabab-grill'],
        price: 160,
        descriptionBn: 'মুচমুচে তাওয়া ফ্রাই চিকেন চাপ।',
        descriptionEn: 'Crispy pan-fried marinated chicken chaap.',
        image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 2,
        isAvailable: true,
        displayOrder: 34,
        rating: 4.7,
        reviewsCount: 88,
      },
      {
        nameBn: 'চিকেন তান্দুরী',
        nameEn: 'Chicken Tandoori',
        slug: 'chicken-tandoori',
        category: catMap['kabab-grill'],
        price: 160,
        descriptionBn: 'মাটির তন্দুরে সেঁকা লাল মসলাদার চিকেন তান্দুরী।',
        descriptionEn: 'Classic clay oven roasted tandoori chicken.',
        image: 'https://images.unsplash.com/photo-1599481238640-4c1288750d7a?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 2,
        isAvailable: true,
        displayOrder: 35,
        rating: 4.8,
        reviewsCount: 95,
      },
      {
        nameBn: 'চিকেন টিক্কা',
        nameEn: 'Chicken Tikka',
        slug: 'chicken-tikka',
        category: catMap['kabab-grill'],
        price: 250,
        descriptionBn: 'সুস্বাদু মাখনে সেঁকা বোনলেস চিকেন টিক্কা।',
        descriptionEn: 'Boneless tender chicken chunks grilled with butter and tikka masala.',
        image: 'https://images.unsplash.com/photo-1599481238640-4c1288750d7a?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 2,
        isAvailable: true,
        displayOrder: 36,
        rating: 4.8,
        reviewsCount: 110,
      },
      {
        nameBn: 'খাসির শর্মা',
        nameEn: 'Mutton Shawarma',
        slug: 'mutton-shawarma',
        category: catMap['kabab-grill'],
        price: 160,
        descriptionBn: 'নরম রুটিতে মোড়ানো খাসির জুসি কিমা ও স্পেশাল মেয়ো সস।',
        descriptionEn: 'Warm pita wrap filled with seasoned shredded mutton and garlic sauce.',
        image: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 1,
        isAvailable: true,
        displayOrder: 37,
        rating: 4.8,
        reviewsCount: 120,
      },
      {
        nameBn: 'চিকেন শর্মা',
        nameEn: 'Chicken Shawarma',
        slug: 'chicken-shawarma',
        category: catMap['kabab-grill'],
        price: 140,
        descriptionBn: 'চিকেন, সালাদ ও রসুনের সসে তৈরি মুখরোচক শর্মা রোল।',
        descriptionEn: 'Rolled pita with grilled spiced chicken, tahini, and pickles.',
        image: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 1,
        isAvailable: true,
        displayOrder: 38,
        rating: 4.7,
        reviewsCount: 135,
      },
      {
        nameBn: 'কোয়ার্টার গ্রিল সিনা',
        nameEn: 'Quarter Grill Chicken',
        slug: 'quarter-grill-chicken',
        category: catMap['kabab-grill'],
        price: 140,
        descriptionBn: 'কয়লার তাপে পোড়া রসালো ১/৪ গ্রিল চিকেন সিনা।',
        descriptionEn: 'Flame-grilled 1/4 chicken breast seasoned with signature herbs.',
        image: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 2,
        isAvailable: true,
        displayOrder: 39,
        rating: 4.8,
        reviewsCount: 100,
      },
      {
        nameBn: 'স্পেশাল মোগলাই পরটা',
        nameEn: 'Special Mughlai Paratha',
        slug: 'special-mughlai-paratha',
        category: catMap['kabab-grill'],
        price: 100,
        descriptionBn: 'ডিম, পেঁয়াজ ও কিমায় তৈরি মুচমুচে শাহি মোগলাই পরটা।',
        descriptionEn: 'Crispy deep-fried flatbread stuffed with spiced egg and minced chicken.',
        image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 1,
        isAvailable: true,
        displayOrder: 40,
        rating: 4.8,
        reviewsCount: 115,
      },
      {
        nameBn: 'গ্রিল চিকেন ফুল (আস্ত মুরগি)',
        nameEn: 'Full Grilled Chicken',
        slug: 'full-grilled-chicken',
        category: catMap['kabab-grill'],
        price: 470,
        descriptionBn: 'কয়লায় পোড়া সম্পূর্ণ আস্ত রসালো গ্রিল চিকেন ও স্পেশাল নান।',
        descriptionEn: 'Whole flame-grilled chicken served with special sauce and salad.',
        image: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 2,
        isAvailable: true,
        isBestseller: true,
        displayOrder: 41,
        rating: 4.9,
        reviewsCount: 180,
      },
      {
        nameBn: 'শাহি স্পেশাল হালিম (প্রতি বাটি)',
        nameEn: 'Shahi Mutton Haleem',
        slug: 'shahi-mutton-haleem',
        category: catMap['kabab-grill'],
        price: 110,
        descriptionBn: '৫ পদের ডাল, গম ও খাসির নরম মাংসে ঘণ্টার পর ঘণ্টা ঘুঁটে তৈরি শাহি হালিম।',
        descriptionEn: 'Rich slow-cooked lentil and shredded mutton stew garnished with fried onions.',
        image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 2,
        isAvailable: true,
        isBestseller: true,
        displayOrder: 42,
        rating: 5.0,
        reviewsCount: 240,
      },

      // ==================== VORTA & GREENS (শাক ও ভর্তা) ====================
      {
        nameBn: 'লাল শাক ভাজি',
        nameEn: 'Lal Shaak',
        slug: 'lal-shaak',
        category: catMap['vorta-greens'],
        price: 40,
        descriptionBn: 'রসুন ও শুকনা মরিচে ভাজা টাটকা লাল শাক।',
        descriptionEn: 'Fresh red spinach sauteed with garlic and dry red chilies.',
        image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 1,
        isAvailable: true,
        displayOrder: 43,
        rating: 4.7,
        reviewsCount: 50,
      },
      {
        nameBn: 'করলা ভাজি',
        nameEn: 'Korola Bhaji',
        slug: 'korola-bhaji',
        category: catMap['vorta-greens'],
        price: 40,
        descriptionBn: 'আলু ও পেঁয়াজে মুচমুচে করে ভাজা তিতাহীন করলা।',
        descriptionEn: 'Crispy bitter gourd stir-fry with sliced potatoes and onions.',
        image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 1,
        isAvailable: true,
        displayOrder: 44,
        rating: 4.6,
        reviewsCount: 40,
      },
      {
        nameBn: 'বেগুন ভর্তা',
        nameEn: 'Begun Vorta',
        slug: 'begun-vorta',
        category: catMap['vorta-greens'],
        price: 40,
        descriptionBn: 'পোড়া বেগুন, কাঁচামরিচ ও সরিষার তেলে মাখানো ভর্তা।',
        descriptionEn: 'Fire-roasted smoked eggplant mashed with mustard oil and chilies.',
        image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 2,
        isAvailable: true,
        displayOrder: 45,
        rating: 4.8,
        reviewsCount: 95,
      },
      {
        nameBn: 'কাঁচাকলা ভর্তা',
        nameEn: 'Kola Vorta',
        slug: 'kola-vorta',
        category: catMap['vorta-greens'],
        price: 40,
        descriptionBn: 'সিদ্ধ কাঁচাকলা ও সরিষার তেলের সুস্বাদু ঐতিহ্যবাহী ভর্তা।',
        descriptionEn: 'Traditional spiced green plantain mash with mustard oil.',
        image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 1,
        isAvailable: true,
        displayOrder: 46,
        rating: 4.7,
        reviewsCount: 60,
      },
      {
        nameBn: 'মাছ ভর্তা',
        nameEn: 'Fish Vorta',
        slug: 'fish-vorta',
        category: catMap['vorta-greens'],
        price: 60,
        descriptionBn: 'টাটকা রুই মাছের কাঁটাহীন স্পেশাল কষা ভর্তা।',
        descriptionEn: 'Deboned fried fish mashed with roasted chili paste and onions.',
        image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 2,
        isAvailable: true,
        displayOrder: 47,
        rating: 4.9,
        reviewsCount: 110,
      },

      // ==================== BREADS & RICE (নান, পরটা ও ভাত) ====================
      {
        nameBn: 'স্পেশাল নান রুটি',
        nameEn: 'Special Naan Ruti',
        slug: 'special-naan-ruti',
        category: catMap['breads-rice'],
        price: 35,
        descriptionBn: 'তন্দুরে তাজা মাখন মাখানো স্পেশাল নান রুটি।',
        descriptionEn: 'Clay oven baked fluffy butter naan.',
        image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 0,
        isAvailable: true,
        displayOrder: 48,
        rating: 4.8,
        reviewsCount: 80,
      },
      {
        nameBn: 'স্পেশাল গার্লিক নান',
        nameEn: 'Special Garlic Naan',
        slug: 'special-garlic-naan',
        category: catMap['breads-rice'],
        price: 70,
        descriptionBn: 'রসুন কুচি ও ধনেপাতায় সুবাসিত গরম গার্লিক নান।',
        descriptionEn: 'Tandoori naan topped with roasted minced garlic and butter.',
        image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 0,
        isAvailable: true,
        displayOrder: 49,
        rating: 4.9,
        reviewsCount: 120,
      },
      {
        nameBn: 'স্পেশাল পরটা',
        nameEn: 'Special Paratha',
        slug: 'special-paratha',
        category: catMap['breads-rice'],
        price: 35,
        descriptionBn: 'ঘিয়ে ভাজা খাস্তা লেয়ার পরটা।',
        descriptionEn: 'Ghee-layered crispy layered paratha.',
        image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 0,
        isAvailable: true,
        displayOrder: 50,
        rating: 4.8,
        reviewsCount: 75,
      },
      {
        nameBn: 'সাদা ভাত',
        nameEn: 'Plain Rice',
        slug: 'plain-rice-dish',
        category: catMap['breads-rice'],
        price: 50,
        descriptionBn: 'ঝরঝরে গরম সাদা নাজিরশাইল চালের ভাত।',
        descriptionEn: 'Steamed fragrant hot Bengali long-grain rice.',
        image: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 0,
        isAvailable: true,
        displayOrder: 51,
        rating: 4.7,
        reviewsCount: 60,
      },

      // ==================== DESSERTS (ডেজার্ট ও মিষ্টি) ====================
      {
        nameBn: 'স্পেশাল ক্যারামেল পুডিং',
        nameEn: 'Special Pudding',
        slug: 'special-pudding',
        category: catMap['desserts'],
        price: 70,
        descriptionBn: 'দুধ ও ডিমের নরম মিষ্টি ক্যারামেল কাস্টার্ড পুডিং।',
        descriptionEn: 'Velvety smooth baked caramel custard pudding.',
        image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 0,
        isAvailable: true,
        displayOrder: 52,
        rating: 4.9,
        reviewsCount: 110,
      },
      {
        nameBn: 'স্পেশাল দুধ চা',
        nameEn: 'Special Milk Tea',
        slug: 'special-milk-tea',
        category: catMap['desserts'],
        price: 35,
        descriptionBn: 'খাঁটি গাভীর দুধের জ্বাল দেওয়া সুবাসিত স্পেশাল চা।',
        descriptionEn: 'Rich, creamy and aromatic slow-brewed milk tea.',
        image: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 0,
        isAvailable: true,
        displayOrder: 53,
        rating: 4.9,
        reviewsCount: 160,
      },
      {
        nameBn: 'শাহি ফালুদা',
        nameEn: 'Royal Faluda',
        slug: 'royal-faluda',
        category: catMap['desserts'],
        price: 120,
        descriptionBn: 'নুডলস, সাবুদানা, ফল, জেলি ও আইসক্রিমে সাজানো শাহি ফালুদা।',
        descriptionEn: 'Chilled dessert drink with vermicelli, basil seeds, fruits and ice cream.',
        image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 0,
        isAvailable: true,
        displayOrder: 54,
        rating: 4.8,
        reviewsCount: 130,
      },
      {
        nameBn: 'স্পেশাল জাফরানি ফিরনি',
        nameEn: 'Special Firni',
        slug: 'special-firni',
        category: catMap['desserts'],
        price: 45,
        originalPrice: 55,
        descriptionBn: 'মাটির পাত্রে জমা ক্ষীর, পেস্তা ও কাজুবাদামে তৈরি ঐতিহ্যবাহী শাহি জাফরানি ফিরনি।',
        descriptionEn: 'Signature rice pudding set in traditional clay pot with saffron and nuts.',
        image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 0,
        isAvailable: true,
        isBestseller: true,
        isFeatured: true,
        displayOrder: 55,
        rating: 5.0,
        reviewsCount: 290,
      },
      {
        nameBn: 'মালাই চপ (প্রতি পিস)',
        nameEn: 'Malai Chop (Per Piece)',
        slug: 'malai-chop-piece',
        category: catMap['desserts'],
        price: 90,
        descriptionBn: 'ক্ষীরে ভেজানো রসালো নরম তুলতুলে মালাই চপ।',
        descriptionEn: 'Soft spongy sweet cottage cheese chop soaked in rich clotted cream.',
        image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 0,
        isAvailable: true,
        displayOrder: 56,
        rating: 4.9,
        reviewsCount: 105,
      },
      {
        nameBn: 'মালাই চপ (প্রতি কেজি)',
        nameEn: 'Malai Chop (1 KG Box)',
        slug: 'malai-chop-kg',
        category: catMap['desserts'],
        price: 900,
        descriptionBn: 'সম্পূর্ণ ১ কেজি স্পেশাল ঘরোয়া মালাই চপের বক্স।',
        descriptionEn: '1 KG box of premium traditional Malai Chop sweets.',
        image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 0,
        isAvailable: true,
        displayOrder: 57,
        rating: 5.0,
        reviewsCount: 75,
      },
      {
        nameBn: 'কাপ দই (বগুড়ার লাল দই)',
        nameEn: 'Cup Doi',
        slug: 'cup-doi',
        category: catMap['desserts'],
        price: 65,
        descriptionBn: 'মাটির কাপে জমা বগুড়ার খাঁটি লাল মিষ্টি দই।',
        descriptionEn: 'Single serving clay cup of authentic caramelized sweet yogurt.',
        image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 0,
        isAvailable: true,
        displayOrder: 58,
        rating: 4.9,
        reviewsCount: 180,
      },
      {
        nameBn: 'খাঁটি মিষ্টি দই (প্রতি কেজি হাঁড়ি)',
        nameEn: 'Sweet Doi (1 KG Pot)',
        slug: 'sweet-doi-kg',
        category: catMap['desserts'],
        price: 360,
        descriptionBn: 'মাটির হাঁড়িতে জমা সম্পূর্ণ ১ কেজি খাঁটি বগুড়ার মিষ্টি দই।',
        descriptionEn: 'Traditional 1 KG clay pot of authentic sweet curd.',
        image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 0,
        isAvailable: true,
        displayOrder: 59,
        rating: 5.0,
        reviewsCount: 140,
      },

      // ==================== DRINKS (পানীয় ও বোরহানি) ====================
      {
        nameBn: 'স্পেশাল বোরহানি (প্রতি গ্লাস)',
        nameEn: 'Special Borhani (Per Glass)',
        slug: 'borhani-glass',
        category: catMap['drinks'],
        price: 50,
        originalPrice: 60,
        descriptionBn: 'টকদই, পুদিনা পাতা, বিট লবণ ও গোপন হজমি মসলায় তৈরি আসল ঘরোয়া স্পেশাল বোরহানি।',
        descriptionEn: 'Famous digestive spiced yogurt beverage with fresh mint and roasted cumin.',
        image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 1,
        isAvailable: true,
        isBestseller: true,
        isFeatured: true,
        displayOrder: 60,
        rating: 5.0,
        reviewsCount: 380,
      },
      {
        nameBn: 'স্পেশাল বোরহানি (১ লিটার বোতল)',
        nameEn: 'Special Borhani (1 Liter Bottle)',
        slug: 'borhani-1-liter',
        category: catMap['drinks'],
        price: 200,
        descriptionBn: 'পারিবারিক পরিবেশনার জন্য সম্পূর্ণ ১ লিটার স্পেশাল বোরহানি বোতল।',
        descriptionEn: '1 Liter chilled family bottle of authentic Gharowa Borhani.',
        image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 1,
        isAvailable: true,
        isBestseller: true,
        displayOrder: 61,
        rating: 5.0,
        reviewsCount: 190,
      },
      {
        nameBn: 'মাল্টা ফ্রেশ জুস',
        nameEn: 'Malta Fresh Juice',
        slug: 'malta-fresh-juice',
        category: catMap['drinks'],
        price: 250,
        descriptionBn: 'টাটকা মাল্টার প্রাকৃতিক সুমিষ্ট ফ্রেশ জুস।',
        descriptionEn: '100% pure freshly squeezed Malta orange juice.',
        image: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 0,
        isAvailable: true,
        displayOrder: 62,
        rating: 4.8,
        reviewsCount: 65,
      },
      {
        nameBn: 'আপেল ফ্রেশ জুস',
        nameEn: 'Apple Fresh Juice',
        slug: 'apple-fresh-juice',
        category: catMap['drinks'],
        price: 250,
        descriptionBn: 'তাজা রসালো আপেলের ফ্রেশ জুস।',
        descriptionEn: 'Freshly extracted pure crisp apple juice.',
        image: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 0,
        isAvailable: true,
        displayOrder: 63,
        rating: 4.7,
        reviewsCount: 55,
      },
      {
        nameBn: 'তরমুজের ফ্রেশ জুস',
        nameEn: 'Watermelon Juice',
        slug: 'watermelon-juice',
        category: catMap['drinks'],
        price: 80,
        descriptionBn: 'ঠান্ডা রিফ্রেশিং লাল তরমুজের শরবত।',
        descriptionEn: 'Chilled, sweet and refreshing fresh watermelon juice.',
        image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 0,
        isAvailable: true,
        displayOrder: 64,
        rating: 4.8,
        reviewsCount: 90,
      },
      {
        nameBn: 'পেঁপে জুস',
        nameEn: 'Papaya Juice',
        slug: 'papaya-juice',
        category: catMap['drinks'],
        price: 80,
        descriptionBn: 'পাকা পেঁপের পুষ্টিকর ও সুস্বাদু স্মুদি জুস।',
        descriptionEn: 'Rich, smooth and healthy ripe papaya juice.',
        image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 0,
        isAvailable: true,
        displayOrder: 65,
        rating: 4.7,
        reviewsCount: 60,
      },
      {
        nameBn: 'স্পেশাল মিষ্টি লাচ্ছি',
        nameEn: 'Special Sweet Lassi',
        slug: 'special-lassi',
        category: catMap['drinks'],
        price: 80,
        descriptionBn: 'ঘন মিষ্টি দই ও বরফের সরভরা রিফ্রেশিং স্পেশাল লাচ্ছি।',
        descriptionEn: 'Thick and frothy traditional sweet yogurt lassi topped with nuts.',
        image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?q=80&w=800&auto=format&fit=crop',
        spiceLevel: 0,
        isAvailable: true,
        displayOrder: 66,
        rating: 4.9,
        reviewsCount: 155,
      },
    ];

    await MenuItem.insertMany(menuItemsData);
    console.log(`[Seed] ${menuItemsData.length} Authentic Menu Board Items seeded successfully.`);

    // 4. Seed Coupons
    console.log('[Seed] Seeding Coupons...');
    await Coupon.deleteMany({});
    await Coupon.create([
      {
        code: 'GH1972',
        titleBn: 'ঐতিহ্যের স্বাদ ৫০ টাকা ছাড়',
        titleEn: 'Heritage Special 50 BDT Off',
        descriptionBn: 'ন্যূনতম ৫০০ টাকার অর্ডারে প্রযোজ্য',
        descriptionEn: 'Applicable on orders over 500 BDT',
        discountType: 'fixed',
        discountValue: 50,
        minOrderAmount: 500,
        maxDiscountAmount: 50,
        startDate: new Date(),
        expiryDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
        maxUsageLimit: 1000,
        isActive: true,
      },
      {
        code: 'GHAROWA10',
        titleBn: '১০% বিশেষ ছাড়',
        titleEn: '10% Special Discount',
        descriptionBn: 'ন্যূনতম ৮০০ টাকার অর্ডারে প্রযোজ্য',
        descriptionEn: 'Applicable on orders over 800 BDT',
        discountType: 'percentage',
        discountValue: 10,
        minOrderAmount: 800,
        maxDiscountAmount: 200,
        startDate: new Date(),
        expiryDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
        maxUsageLimit: 1000,
        isActive: true,
      },
    ]);

    // 5. Seed Restaurant CMS Settings
    console.log('[Seed] Seeding Restaurant Settings CMS...');
    await RestaurantSettings.deleteMany({});
    await RestaurantSettings.create({
      restaurantNameBn: 'ঘরোয়া হোটেল এন্ড রেস্টুরেন্ট',
      restaurantNameEn: 'Gharowa Hotel & Restaurant',
      taglineBn: '১৯৭২ সাল থেকে মতিঝিলের ঐতিহ্যের স্বাদ',
      taglineEn: 'Serving Authentic Bengali Heritage Since 1972',
      phone: '+8801973255888',
      whatsappNumber: '8801973255888',
      email: 'info@gharowarestaurant.com',
      addressBn: '৯/সি মতিঝিল বা/এ, ঢাকা-১০০০ (মেট্রোরেল স্টেশন সংলগ্ন)',
      addressEn: '9/C Motijheel C/A, Dhaka-1000, Bangladesh',
      openingHoursBn: 'সকাল ৭:০০ - রাত ১১:৩০ (প্রতিদিন খোলা)',
      openingHoursEn: '7:00 AM - 11:30 PM (Open Everyday)',
      standardDeliveryFee: 60,
      freeDeliveryThreshold: 1500,
      minOrderAmount: 150,
      heroTitleBn: 'ঐতিহ্যবাহী খাসির ভুনা খিচুড়ি',
      heroTitleEn: 'AUTHENTIC MUTTON KHICHURI',
      heroSubtitleBn: '১৯৭২ সাল থেকে ঢাকার মতিঝিলের ঐতিহ্যবাহী খাসির ভুনা খিচুড়ি, লেগ খিচুড়ি, স্পেশাল কাচ্চি ও বোরহানি।',
      heroSubtitleEn: 'Traditional taste, rich aroma and perfectly cooked mutton. 50+ years of trust.',
      heroBadgeBn: 'ঐতিহ্যবাহী স্বাদ',
      heroBadgeEn: 'AUTHENTIC',
      heroImageUrl: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?q=80&w=1000&auto=format&fit=crop',
      heroPouringImageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?q=80&w=800&auto=format&fit=crop',
      heroCtaTextBn: 'অর্ডার করুন',
      heroCtaTextEn: 'Order Now',
      heroCtaLink: '/menu',
      aboutTitleBn: 'আমাদের ঐতিহ্য ও গল্প',
      aboutTitleEn: 'Our Heritage Story',
      aboutDescBn: '১৯৭২ সালে মতিঝিলের প্রাণকেন্দ্রে শুরু হয় ঘরোয়ার যাত্রা। বিগত ৫ দশকেরও বেশি সময় ধরে আমরা ধরে রেখেছি খাঁটি ঢাকাইয়া রান্নার অতুলনীয় ঐতিহ্য ও স্বাদ।',
      aboutDescEn: 'Gharowa Hotel & Restaurant started in 1972 with a simple goal — to serve authentic Bengali flavors with the best quality and love. Our Mutton Khichuri is our signature dish loved by thousands.',
      aboutImageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=1000&auto=format&fit=crop',
      aboutStats: [
        { labelBn: 'বছরের ঐতিহ্য', labelEn: 'Years Heritage', value: '50+' },
        { labelBn: 'সন্তুষ্ট ভোজনরসিক', labelEn: 'Happy Customers', value: '100K+' },
        { labelBn: 'খাঁটি উপাদান', labelEn: 'Fresh Ingredients', value: '100%' },
        { labelBn: 'গ্রাহক রেটিং', labelEn: 'Customer Rating', value: '4.9 ★' },
      ],
      chefName: 'Chef Rahman',
      chefDesignation: 'Executive Master Chef',
      chefBioBn: '২৫ বছরেরও বেশি রন্ধন অভিজ্ঞতায় ঐতিহ্যবাহী মসলা ও খাঁটি ঘরোয়া স্বাদের ধারক।',
      chefBioEn: 'Over 25 years of mastery in authentic slow-cooked traditional Bangladeshi heritage cuisine.',
      chefExperience: '25+ Years Experience',
      chefSpecialty: 'Dum Pukht & Heritage Khichuri',
      chefImageUrl: 'https://images.unsplash.com/photo-1577219491135-ce391730fb2c?q=80&w=800&auto=format&fit=crop',
      ownerName: 'Alhaj Md. Sirajuddin',
      ownerDesignation: 'Founder & Visionary (Since 1972)',
      ownerStoryBn: '১৯৭২ সালে মতিঝিলে ছোট্ট পরিসরে শুরু করা ঘরোয়া আজ ঢাকার ঐতিহ্যের অংশ। আমাদের অঙ্গীকার কেবল মান ও খাঁটি স্বাদ।',
      ownerStoryEn: 'Founded with the philosophy that great food brings families and hearts together with honesty and passion.',
      ownerQuoteBn: 'স্বাদ যেখানে স্মৃতি, তৃপ্তি যেখানে প্রতিশ্রুতি।',
      ownerQuoteEn: 'Where culinary tradition meets timeless hospitality.',
      ownerImageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=800&auto=format&fit=crop',
      menuBoardImageUrl: '',
      isMenuBoardEnabled: true,
    });

    console.log('[Seed] Database seeded successfully with all authentic menu board items and categories!');
    process.exit(0);
  } catch (error) {
    console.error('[Seed] Database seed error:', error);
    process.exit(1);
  }
};

if (require.main === module) {
  seedDatabase();
}
